# automatically generated, do not edit

# (source: FIX44.xml)

from pyfix.fix.context import FixFieldDescriptor, FixGroupDescriptor

__all__ = ['FIX_HEADER_FIELD_IDS', 'FIX_TRAILER_FIELD_IDS', '_fix_field_types', '_fix_message_types', '_fix_group_types', '_fix_field_numbers', '_fix_group_numbers', '_fix_msgtype_table']

FIX_HEADER_FIELD_IDS = [
	8, 9, 35, 49, 56, 115, 128, 90, 91, 34, 50, 142, 57, 143, 116, 144, 129, 145, 43, 97, 52, 122, 212, 213, 347, 369]

FIX_TRAILER_FIELD_IDS = [10, 89, 93]

_fix_field_types = {
	'Account': FixFieldDescriptor('Account', 1, 'STRING', str),
	'AccountType': FixFieldDescriptor('AccountType', 581, 'INT', int),
	'AccruedInterestAmt': FixFieldDescriptor('AccruedInterestAmt', 159, 'AMT', float),
	'AccruedInterestRate': FixFieldDescriptor('AccruedInterestRate', 158, 'PERCENTAGE', float),
	'AcctIDSource': FixFieldDescriptor('AcctIDSource', 660, 'INT', int),
	'Adjustment': FixFieldDescriptor('Adjustment', 334, 'INT', int),
	'AdjustmentType': FixFieldDescriptor('AdjustmentType', 718, 'INT', int),
	'AdvId': FixFieldDescriptor('AdvId', 2, 'STRING', str),
	'AdvRefID': FixFieldDescriptor('AdvRefID', 3, 'STRING', str),
	'AdvSide': FixFieldDescriptor('AdvSide', 4, 'CHAR', str),
	'AdvTransType': FixFieldDescriptor('AdvTransType', 5, 'STRING', str),
	'AffectedOrderID': FixFieldDescriptor('AffectedOrderID', 535, 'STRING', str),
	'AffectedSecondaryOrderID': FixFieldDescriptor('AffectedSecondaryOrderID', 536, 'STRING', str),
	'AffirmStatus': FixFieldDescriptor('AffirmStatus', 940, 'INT', int),
	'AggregatedBook': FixFieldDescriptor('AggregatedBook', 266, 'BOOLEAN', str),
	'AgreementCurrency': FixFieldDescriptor('AgreementCurrency', 918, 'CURRENCY', str),
	'AgreementDate': FixFieldDescriptor('AgreementDate', 915, 'LOCALMKTDATE', str),
	'AgreementDesc': FixFieldDescriptor('AgreementDesc', 913, 'STRING', str),
	'AgreementID': FixFieldDescriptor('AgreementID', 914, 'STRING', str),
	'AllocAccount': FixFieldDescriptor('AllocAccount', 79, 'STRING', str),
	'AllocAccountType': FixFieldDescriptor('AllocAccountType', 798, 'INT', int),
	'AllocAccruedInterestAmt': FixFieldDescriptor('AllocAccruedInterestAmt', 742, 'AMT', float),
	'AllocAcctIDSource': FixFieldDescriptor('AllocAcctIDSource', 661, 'INT', int),
	'AllocAvgPx': FixFieldDescriptor('AllocAvgPx', 153, 'PRICE', float),
	'AllocCancReplaceReason': FixFieldDescriptor('AllocCancReplaceReason', 796, 'INT', int),
	'AllocHandlInst': FixFieldDescriptor('AllocHandlInst', 209, 'INT', int),
	'AllocID': FixFieldDescriptor('AllocID', 70, 'STRING', str),
	'AllocInterestAtMaturity': FixFieldDescriptor('AllocInterestAtMaturity', 741, 'AMT', float),
	'AllocIntermedReqType': FixFieldDescriptor('AllocIntermedReqType', 808, 'INT', int),
	'AllocLinkID': FixFieldDescriptor('AllocLinkID', 196, 'STRING', str),
	'AllocLinkType': FixFieldDescriptor('AllocLinkType', 197, 'INT', int),
	'AllocNetMoney': FixFieldDescriptor('AllocNetMoney', 154, 'AMT', float),
	'AllocNoOrdersType': FixFieldDescriptor('AllocNoOrdersType', 857, 'INT', int),
	'AllocPrice': FixFieldDescriptor('AllocPrice', 366, 'PRICE', float),
	'AllocQty': FixFieldDescriptor('AllocQty', 80, 'QTY', float),
	'AllocRejCode': FixFieldDescriptor('AllocRejCode', 88, 'INT', int),
	'AllocReportID': FixFieldDescriptor('AllocReportID', 755, 'STRING', str),
	'AllocReportRefID': FixFieldDescriptor('AllocReportRefID', 795, 'STRING', str),
	'AllocReportType': FixFieldDescriptor('AllocReportType', 794, 'INT', int),
	'AllocSettlCurrAmt': FixFieldDescriptor('AllocSettlCurrAmt', 737, 'AMT', float),
	'AllocSettlCurrency': FixFieldDescriptor('AllocSettlCurrency', 736, 'CURRENCY', str),
	'AllocSettlInstType': FixFieldDescriptor('AllocSettlInstType', 780, 'INT', int),
	'AllocStatus': FixFieldDescriptor('AllocStatus', 87, 'INT', int),
	'AllocText': FixFieldDescriptor('AllocText', 161, 'STRING', str),
	'AllocTransType': FixFieldDescriptor('AllocTransType', 71, 'CHAR', str),
	'AllocType': FixFieldDescriptor('AllocType', 626, 'INT', int),
	'AllowableOneSidednessCurr': FixFieldDescriptor('AllowableOneSidednessCurr', 767, 'CURRENCY', str),
	'AllowableOneSidednessPct': FixFieldDescriptor('AllowableOneSidednessPct', 765, 'PERCENTAGE', float),
	'AllowableOneSidednessValue': FixFieldDescriptor('AllowableOneSidednessValue', 766, 'AMT', float),
	'AltMDSourceID': FixFieldDescriptor('AltMDSourceID', 817, 'STRING', str),
	'ApplQueueAction': FixFieldDescriptor('ApplQueueAction', 815, 'INT', int),
	'ApplQueueDepth': FixFieldDescriptor('ApplQueueDepth', 813, 'INT', int),
	'ApplQueueMax': FixFieldDescriptor('ApplQueueMax', 812, 'INT', int),
	'ApplQueueResolution': FixFieldDescriptor('ApplQueueResolution', 814, 'INT', int),
	'AsgnReqID': FixFieldDescriptor('AsgnReqID', 831, 'STRING', str),
	'AsgnRptID': FixFieldDescriptor('AsgnRptID', 833, 'STRING', str),
	'AssignmentMethod': FixFieldDescriptor('AssignmentMethod', 744, 'CHAR', str),
	'AssignmentUnit': FixFieldDescriptor('AssignmentUnit', 745, 'QTY', float),
	'AutoAcceptIndicator': FixFieldDescriptor('AutoAcceptIndicator', 754, 'BOOLEAN', str),
	'AvgParPx': FixFieldDescriptor('AvgParPx', 860, 'PRICE', float),
	'AvgPx': FixFieldDescriptor('AvgPx', 6, 'PRICE', float),
	'AvgPxIndicator': FixFieldDescriptor('AvgPxIndicator', 819, 'INT', int),
	'AvgPxPrecision': FixFieldDescriptor('AvgPxPrecision', 74, 'INT', int),
	'BasisFeatureDate': FixFieldDescriptor('BasisFeatureDate', 259, 'LOCALMKTDATE', str),
	'BasisFeaturePrice': FixFieldDescriptor('BasisFeaturePrice', 260, 'PRICE', float),
	'BasisPxType': FixFieldDescriptor('BasisPxType', 419, 'CHAR', str),
	'BeginSeqNo': FixFieldDescriptor('BeginSeqNo', 7, 'SEQNUM', int),
	'BeginString': FixFieldDescriptor('BeginString', 8, 'STRING', str),
	'BenchmarkCurveCurrency': FixFieldDescriptor('BenchmarkCurveCurrency', 220, 'CURRENCY', str),
	'BenchmarkCurveName': FixFieldDescriptor('BenchmarkCurveName', 221, 'STRING', str),
	'BenchmarkCurvePoint': FixFieldDescriptor('BenchmarkCurvePoint', 222, 'STRING', str),
	'BenchmarkPrice': FixFieldDescriptor('BenchmarkPrice', 662, 'PRICE', float),
	'BenchmarkPriceType': FixFieldDescriptor('BenchmarkPriceType', 663, 'INT', int),
	'BenchmarkSecurityID': FixFieldDescriptor('BenchmarkSecurityID', 699, 'STRING', str),
	'BenchmarkSecurityIDSource': FixFieldDescriptor('BenchmarkSecurityIDSource', 761, 'STRING', str),
	'BidDescriptor': FixFieldDescriptor('BidDescriptor', 400, 'STRING', str),
	'BidDescriptorType': FixFieldDescriptor('BidDescriptorType', 399, 'INT', int),
	'BidForwardPoints': FixFieldDescriptor('BidForwardPoints', 189, 'PRICEOFFSET', float),
	'BidForwardPoints2': FixFieldDescriptor('BidForwardPoints2', 642, 'PRICEOFFSET', float),
	'BidID': FixFieldDescriptor('BidID', 390, 'STRING', str),
	'BidPx': FixFieldDescriptor('BidPx', 132, 'PRICE', float),
	'BidRequestTransType': FixFieldDescriptor('BidRequestTransType', 374, 'CHAR', str),
	'BidSize': FixFieldDescriptor('BidSize', 134, 'QTY', float),
	'BidSpotRate': FixFieldDescriptor('BidSpotRate', 188, 'PRICE', float),
	'BidTradeType': FixFieldDescriptor('BidTradeType', 418, 'CHAR', str),
	'BidType': FixFieldDescriptor('BidType', 394, 'INT', int),
	'BidYield': FixFieldDescriptor('BidYield', 632, 'PERCENTAGE', float),
	'BodyLength': FixFieldDescriptor('BodyLength', 9, 'LENGTH', str),
	'BookingRefID': FixFieldDescriptor('BookingRefID', 466, 'STRING', str),
	'BookingType': FixFieldDescriptor('BookingType', 775, 'INT', int),
	'BookingUnit': FixFieldDescriptor('BookingUnit', 590, 'CHAR', str),
	'BusinessRejectReason': FixFieldDescriptor('BusinessRejectReason', 380, 'INT', int),
	'BusinessRejectRefID': FixFieldDescriptor('BusinessRejectRefID', 379, 'STRING', str),
	'BuyVolume': FixFieldDescriptor('BuyVolume', 330, 'QTY', float),
	'CFICode': FixFieldDescriptor('CFICode', 461, 'STRING', str),
	'CPProgram': FixFieldDescriptor('CPProgram', 875, 'INT', int),
	'CPRegType': FixFieldDescriptor('CPRegType', 876, 'STRING', str),
	'CancellationRights': FixFieldDescriptor('CancellationRights', 480, 'CHAR', str),
	'CardExpDate': FixFieldDescriptor('CardExpDate', 490, 'LOCALMKTDATE', str),
	'CardHolderName': FixFieldDescriptor('CardHolderName', 488, 'STRING', str),
	'CardIssNum': FixFieldDescriptor('CardIssNum', 491, 'STRING', str),
	'CardNumber': FixFieldDescriptor('CardNumber', 489, 'STRING', str),
	'CardStartDate': FixFieldDescriptor('CardStartDate', 503, 'LOCALMKTDATE', str),
	'CashDistribAgentAcctName': FixFieldDescriptor('CashDistribAgentAcctName', 502, 'STRING', str),
	'CashDistribAgentAcctNumber': FixFieldDescriptor('CashDistribAgentAcctNumber', 500, 'STRING', str),
	'CashDistribAgentCode': FixFieldDescriptor('CashDistribAgentCode', 499, 'STRING', str),
	'CashDistribAgentName': FixFieldDescriptor('CashDistribAgentName', 498, 'STRING', str),
	'CashDistribCurr': FixFieldDescriptor('CashDistribCurr', 478, 'CURRENCY', str),
	'CashDistribPayRef': FixFieldDescriptor('CashDistribPayRef', 501, 'STRING', str),
	'CashMargin': FixFieldDescriptor('CashMargin', 544, 'CHAR', str),
	'CashOrderQty': FixFieldDescriptor('CashOrderQty', 152, 'QTY', float),
	'CashOutstanding': FixFieldDescriptor('CashOutstanding', 901, 'AMT', float),
	'CheckSum': FixFieldDescriptor('CheckSum', 10, 'STRING', str),
	'ClOrdID': FixFieldDescriptor('ClOrdID', 11, 'STRING', str),
	'ClOrdLinkID': FixFieldDescriptor('ClOrdLinkID', 583, 'STRING', str),
	'ClearingBusinessDate': FixFieldDescriptor('ClearingBusinessDate', 715, 'LOCALMKTDATE', str),
	'ClearingFeeIndicator': FixFieldDescriptor('ClearingFeeIndicator', 635, 'STRING', str),
	'ClearingInstruction': FixFieldDescriptor('ClearingInstruction', 577, 'INT', int),
	'ClientBidID': FixFieldDescriptor('ClientBidID', 391, 'STRING', str),
	'CollAction': FixFieldDescriptor('CollAction', 944, 'INT', int),
	'CollAsgnID': FixFieldDescriptor('CollAsgnID', 902, 'STRING', str),
	'CollAsgnReason': FixFieldDescriptor('CollAsgnReason', 895, 'INT', int),
	'CollAsgnRefID': FixFieldDescriptor('CollAsgnRefID', 907, 'STRING', str),
	'CollAsgnRejectReason': FixFieldDescriptor('CollAsgnRejectReason', 906, 'INT', int),
	'CollAsgnRespType': FixFieldDescriptor('CollAsgnRespType', 905, 'INT', int),
	'CollAsgnTransType': FixFieldDescriptor('CollAsgnTransType', 903, 'INT', int),
	'CollInquiryID': FixFieldDescriptor('CollInquiryID', 909, 'STRING', str),
	'CollInquiryQualifier': FixFieldDescriptor('CollInquiryQualifier', 896, 'INT', int),
	'CollInquiryResult': FixFieldDescriptor('CollInquiryResult', 946, 'INT', int),
	'CollInquiryStatus': FixFieldDescriptor('CollInquiryStatus', 945, 'INT', int),
	'CollReqID': FixFieldDescriptor('CollReqID', 894, 'STRING', str),
	'CollRespID': FixFieldDescriptor('CollRespID', 904, 'STRING', str),
	'CollRptID': FixFieldDescriptor('CollRptID', 908, 'STRING', str),
	'CollStatus': FixFieldDescriptor('CollStatus', 910, 'INT', int),
	'CommCurrency': FixFieldDescriptor('CommCurrency', 479, 'CURRENCY', str),
	'CommType': FixFieldDescriptor('CommType', 13, 'CHAR', str),
	'Commission': FixFieldDescriptor('Commission', 12, 'AMT', float),
	'ComplianceID': FixFieldDescriptor('ComplianceID', 376, 'STRING', str),
	'Concession': FixFieldDescriptor('Concession', 238, 'AMT', float),
	'ConfirmID': FixFieldDescriptor('ConfirmID', 664, 'STRING', str),
	'ConfirmRefID': FixFieldDescriptor('ConfirmRefID', 772, 'STRING', str),
	'ConfirmRejReason': FixFieldDescriptor('ConfirmRejReason', 774, 'INT', int),
	'ConfirmReqID': FixFieldDescriptor('ConfirmReqID', 859, 'STRING', str),
	'ConfirmStatus': FixFieldDescriptor('ConfirmStatus', 665, 'INT', int),
	'ConfirmTransType': FixFieldDescriptor('ConfirmTransType', 666, 'INT', int),
	'ConfirmType': FixFieldDescriptor('ConfirmType', 773, 'INT', int),
	'ContAmtCurr': FixFieldDescriptor('ContAmtCurr', 521, 'CURRENCY', str),
	'ContAmtType': FixFieldDescriptor('ContAmtType', 519, 'INT', int),
	'ContAmtValue': FixFieldDescriptor('ContAmtValue', 520, 'FLOAT', float),
	'ContraBroker': FixFieldDescriptor('ContraBroker', 375, 'STRING', str),
	'ContraLegRefID': FixFieldDescriptor('ContraLegRefID', 655, 'STRING', str),
	'ContraTradeQty': FixFieldDescriptor('ContraTradeQty', 437, 'QTY', float),
	'ContraTradeTime': FixFieldDescriptor('ContraTradeTime', 438, 'UTCTIMESTAMP', str),
	'ContraTrader': FixFieldDescriptor('ContraTrader', 337, 'STRING', str),
	'ContractMultiplier': FixFieldDescriptor('ContractMultiplier', 231, 'FLOAT', float),
	'ContractSettlMonth': FixFieldDescriptor('ContractSettlMonth', 667, 'MONTHYEAR', str),
	'ContraryInstructionIndicator': FixFieldDescriptor('ContraryInstructionIndicator', 719, 'BOOLEAN', str),
	'CopyMsgIndicator': FixFieldDescriptor('CopyMsgIndicator', 797, 'BOOLEAN', str),
	'CorporateAction': FixFieldDescriptor('CorporateAction', 292, 'MULTIPLEVALUESTRING', str),
	'Country': FixFieldDescriptor('Country', 421, 'COUNTRY', str),
	'CountryOfIssue': FixFieldDescriptor('CountryOfIssue', 470, 'COUNTRY', str),
	'CouponPaymentDate': FixFieldDescriptor('CouponPaymentDate', 224, 'LOCALMKTDATE', str),
	'CouponRate': FixFieldDescriptor('CouponRate', 223, 'PERCENTAGE', float),
	'CoveredOrUncovered': FixFieldDescriptor('CoveredOrUncovered', 203, 'INT', int),
	'CreditRating': FixFieldDescriptor('CreditRating', 255, 'STRING', str),
	'CrossID': FixFieldDescriptor('CrossID', 548, 'STRING', str),
	'CrossPercent': FixFieldDescriptor('CrossPercent', 413, 'PERCENTAGE', float),
	'CrossPrioritization': FixFieldDescriptor('CrossPrioritization', 550, 'INT', int),
	'CrossType': FixFieldDescriptor('CrossType', 549, 'INT', int),
	'CumQty': FixFieldDescriptor('CumQty', 14, 'QTY', float),
	'Currency': FixFieldDescriptor('Currency', 15, 'CURRENCY', str),
	'CustOrderCapacity': FixFieldDescriptor('CustOrderCapacity', 582, 'INT', int),
	'CxlQty': FixFieldDescriptor('CxlQty', 84, 'QTY', float),
	'CxlRejReason': FixFieldDescriptor('CxlRejReason', 102, 'INT', int),
	'CxlRejResponseTo': FixFieldDescriptor('CxlRejResponseTo', 434, 'CHAR', str),
	'DKReason': FixFieldDescriptor('DKReason', 127, 'CHAR', str),
	'DateOfBirth': FixFieldDescriptor('DateOfBirth', 486, 'LOCALMKTDATE', str),
	'DatedDate': FixFieldDescriptor('DatedDate', 873, 'LOCALMKTDATE', str),
	'DayAvgPx': FixFieldDescriptor('DayAvgPx', 426, 'PRICE', float),
	'DayBookingInst': FixFieldDescriptor('DayBookingInst', 589, 'CHAR', str),
	'DayCumQty': FixFieldDescriptor('DayCumQty', 425, 'QTY', float),
	'DayOrderQty': FixFieldDescriptor('DayOrderQty', 424, 'QTY', float),
	'DefBidSize': FixFieldDescriptor('DefBidSize', 293, 'QTY', float),
	'DefOfferSize': FixFieldDescriptor('DefOfferSize', 294, 'QTY', float),
	'DeleteReason': FixFieldDescriptor('DeleteReason', 285, 'CHAR', str),
	'DeliverToCompID': FixFieldDescriptor('DeliverToCompID', 128, 'STRING', str),
	'DeliverToLocationID': FixFieldDescriptor('DeliverToLocationID', 145, 'STRING', str),
	'DeliverToSubID': FixFieldDescriptor('DeliverToSubID', 129, 'STRING', str),
	'DeliveryDate': FixFieldDescriptor('DeliveryDate', 743, 'LOCALMKTDATE', str),
	'DeliveryForm': FixFieldDescriptor('DeliveryForm', 668, 'INT', int),
	'DeliveryType': FixFieldDescriptor('DeliveryType', 919, 'INT', int),
	'Designation': FixFieldDescriptor('Designation', 494, 'STRING', str),
	'DeskID': FixFieldDescriptor('DeskID', 284, 'STRING', str),
	'DiscretionInst': FixFieldDescriptor('DiscretionInst', 388, 'CHAR', str),
	'DiscretionLimitType': FixFieldDescriptor('DiscretionLimitType', 843, 'INT', int),
	'DiscretionMoveType': FixFieldDescriptor('DiscretionMoveType', 841, 'INT', int),
	'DiscretionOffsetType': FixFieldDescriptor('DiscretionOffsetType', 842, 'INT', int),
	'DiscretionOffsetValue': FixFieldDescriptor('DiscretionOffsetValue', 389, 'FLOAT', float),
	'DiscretionPrice': FixFieldDescriptor('DiscretionPrice', 845, 'PRICE', float),
	'DiscretionRoundDirection': FixFieldDescriptor('DiscretionRoundDirection', 844, 'INT', int),
	'DiscretionScope': FixFieldDescriptor('DiscretionScope', 846, 'INT', int),
	'DistribPaymentMethod': FixFieldDescriptor('DistribPaymentMethod', 477, 'INT', int),
	'DistribPercentage': FixFieldDescriptor('DistribPercentage', 512, 'PERCENTAGE', float),
	'DlvyInstType': FixFieldDescriptor('DlvyInstType', 787, 'CHAR', str),
	'DueToRelated': FixFieldDescriptor('DueToRelated', 329, 'BOOLEAN', str),
	'EFPTrackingError': FixFieldDescriptor('EFPTrackingError', 405, 'PERCENTAGE', float),
	'EffectiveTime': FixFieldDescriptor('EffectiveTime', 168, 'UTCTIMESTAMP', str),
	'EmailThreadID': FixFieldDescriptor('EmailThreadID', 164, 'STRING', str),
	'EmailType': FixFieldDescriptor('EmailType', 94, 'CHAR', str),
	'EncodedAllocText': FixFieldDescriptor('EncodedAllocText', 361, 'DATA', str),
	'EncodedAllocTextLen': FixFieldDescriptor('EncodedAllocTextLen', 360, 'LENGTH', str),
	'EncodedHeadline': FixFieldDescriptor('EncodedHeadline', 359, 'DATA', str),
	'EncodedHeadlineLen': FixFieldDescriptor('EncodedHeadlineLen', 358, 'LENGTH', str),
	'EncodedIssuer': FixFieldDescriptor('EncodedIssuer', 349, 'DATA', str),
	'EncodedIssuerLen': FixFieldDescriptor('EncodedIssuerLen', 348, 'LENGTH', str),
	'EncodedLegIssuer': FixFieldDescriptor('EncodedLegIssuer', 619, 'DATA', str),
	'EncodedLegIssuerLen': FixFieldDescriptor('EncodedLegIssuerLen', 618, 'LENGTH', str),
	'EncodedLegSecurityDesc': FixFieldDescriptor('EncodedLegSecurityDesc', 622, 'DATA', str),
	'EncodedLegSecurityDescLen': FixFieldDescriptor('EncodedLegSecurityDescLen', 621, 'LENGTH', str),
	'EncodedListExecInst': FixFieldDescriptor('EncodedListExecInst', 353, 'DATA', str),
	'EncodedListExecInstLen': FixFieldDescriptor('EncodedListExecInstLen', 352, 'LENGTH', str),
	'EncodedListStatusText': FixFieldDescriptor('EncodedListStatusText', 446, 'DATA', str),
	'EncodedListStatusTextLen': FixFieldDescriptor('EncodedListStatusTextLen', 445, 'LENGTH', str),
	'EncodedSecurityDesc': FixFieldDescriptor('EncodedSecurityDesc', 351, 'DATA', str),
	'EncodedSecurityDescLen': FixFieldDescriptor('EncodedSecurityDescLen', 350, 'LENGTH', str),
	'EncodedSubject': FixFieldDescriptor('EncodedSubject', 357, 'DATA', str),
	'EncodedSubjectLen': FixFieldDescriptor('EncodedSubjectLen', 356, 'LENGTH', str),
	'EncodedText': FixFieldDescriptor('EncodedText', 355, 'DATA', str),
	'EncodedTextLen': FixFieldDescriptor('EncodedTextLen', 354, 'LENGTH', str),
	'EncodedUnderlyingIssuer': FixFieldDescriptor('EncodedUnderlyingIssuer', 363, 'DATA', str),
	'EncodedUnderlyingIssuerLen': FixFieldDescriptor('EncodedUnderlyingIssuerLen', 362, 'LENGTH', str),
	'EncodedUnderlyingSecurityDesc': FixFieldDescriptor('EncodedUnderlyingSecurityDesc', 365, 'DATA', str),
	'EncodedUnderlyingSecurityDescLen': FixFieldDescriptor('EncodedUnderlyingSecurityDescLen', 364, 'LENGTH', str),
	'EncryptMethod': FixFieldDescriptor('EncryptMethod', 98, 'INT', int),
	'EndAccruedInterestAmt': FixFieldDescriptor('EndAccruedInterestAmt', 920, 'AMT', float),
	'EndCash': FixFieldDescriptor('EndCash', 922, 'AMT', float),
	'EndDate': FixFieldDescriptor('EndDate', 917, 'LOCALMKTDATE', str),
	'EndSeqNo': FixFieldDescriptor('EndSeqNo', 16, 'SEQNUM', int),
	'EventDate': FixFieldDescriptor('EventDate', 866, 'LOCALMKTDATE', str),
	'EventPx': FixFieldDescriptor('EventPx', 867, 'PRICE', float),
	'EventText': FixFieldDescriptor('EventText', 868, 'STRING', str),
	'EventType': FixFieldDescriptor('EventType', 865, 'INT', int),
	'ExDate': FixFieldDescriptor('ExDate', 230, 'LOCALMKTDATE', str),
	'ExDestination': FixFieldDescriptor('ExDestination', 100, 'EXCHANGE', str),
	'ExchangeForPhysical': FixFieldDescriptor('ExchangeForPhysical', 411, 'BOOLEAN', str),
	'ExchangeRule': FixFieldDescriptor('ExchangeRule', 825, 'STRING', str),
	'ExecID': FixFieldDescriptor('ExecID', 17, 'STRING', str),
	'ExecInst': FixFieldDescriptor('ExecInst', 18, 'MULTIPLEVALUESTRING', str),
	'ExecPriceAdjustment': FixFieldDescriptor('ExecPriceAdjustment', 485, 'FLOAT', float),
	'ExecPriceType': FixFieldDescriptor('ExecPriceType', 484, 'CHAR', str),
	'ExecRefID': FixFieldDescriptor('ExecRefID', 19, 'STRING', str),
	'ExecRestatementReason': FixFieldDescriptor('ExecRestatementReason', 378, 'INT', int),
	'ExecType': FixFieldDescriptor('ExecType', 150, 'CHAR', str),
	'ExecValuationPoint': FixFieldDescriptor('ExecValuationPoint', 515, 'UTCTIMESTAMP', str),
	'ExerciseMethod': FixFieldDescriptor('ExerciseMethod', 747, 'CHAR', str),
	'ExpirationCycle': FixFieldDescriptor('ExpirationCycle', 827, 'INT', int),
	'ExpireDate': FixFieldDescriptor('ExpireDate', 432, 'LOCALMKTDATE', str),
	'ExpireTime': FixFieldDescriptor('ExpireTime', 126, 'UTCTIMESTAMP', str),
	'Factor': FixFieldDescriptor('Factor', 228, 'FLOAT', float),
	'FairValue': FixFieldDescriptor('FairValue', 406, 'AMT', float),
	'FinancialStatus': FixFieldDescriptor('FinancialStatus', 291, 'MULTIPLEVALUESTRING', str),
	'ForexReq': FixFieldDescriptor('ForexReq', 121, 'BOOLEAN', str),
	'FundRenewWaiv': FixFieldDescriptor('FundRenewWaiv', 497, 'CHAR', str),
	'GTBookingInst': FixFieldDescriptor('GTBookingInst', 427, 'INT', int),
	'GapFillFlag': FixFieldDescriptor('GapFillFlag', 123, 'BOOLEAN', str),
	'GrossTradeAmt': FixFieldDescriptor('GrossTradeAmt', 381, 'AMT', float),
	'HaltReason': FixFieldDescriptor('HaltReason', 327, 'CHAR', str),
	'HandlInst': FixFieldDescriptor('HandlInst', 21, 'CHAR', str),
	'Headline': FixFieldDescriptor('Headline', 148, 'STRING', str),
	'HeartBtInt': FixFieldDescriptor('HeartBtInt', 108, 'INT', int),
	'HighPx': FixFieldDescriptor('HighPx', 332, 'PRICE', float),
	'HopCompID': FixFieldDescriptor('HopCompID', 628, 'STRING', str),
	'HopRefID': FixFieldDescriptor('HopRefID', 630, 'SEQNUM', int),
	'HopSendingTime': FixFieldDescriptor('HopSendingTime', 629, 'UTCTIMESTAMP', str),
	'IOINaturalFlag': FixFieldDescriptor('IOINaturalFlag', 130, 'BOOLEAN', str),
	'IOIQltyInd': FixFieldDescriptor('IOIQltyInd', 25, 'CHAR', str),
	'IOIQty': FixFieldDescriptor('IOIQty', 27, 'STRING', str),
	'IOIQualifier': FixFieldDescriptor('IOIQualifier', 104, 'CHAR', str),
	'IOIRefID': FixFieldDescriptor('IOIRefID', 26, 'STRING', str),
	'IOITransType': FixFieldDescriptor('IOITransType', 28, 'CHAR', str),
	'IOIid': FixFieldDescriptor('IOIid', 23, 'STRING', str),
	'InViewOfCommon': FixFieldDescriptor('InViewOfCommon', 328, 'BOOLEAN', str),
	'IncTaxInd': FixFieldDescriptor('IncTaxInd', 416, 'INT', int),
	'IndividualAllocID': FixFieldDescriptor('IndividualAllocID', 467, 'STRING', str),
	'IndividualAllocRejCode': FixFieldDescriptor('IndividualAllocRejCode', 776, 'INT', int),
	'InstrAttribType': FixFieldDescriptor('InstrAttribType', 871, 'INT', int),
	'InstrAttribValue': FixFieldDescriptor('InstrAttribValue', 872, 'STRING', str),
	'InstrRegistry': FixFieldDescriptor('InstrRegistry', 543, 'STRING', str),
	'InterestAccrualDate': FixFieldDescriptor('InterestAccrualDate', 874, 'LOCALMKTDATE', str),
	'InterestAtMaturity': FixFieldDescriptor('InterestAtMaturity', 738, 'AMT', float),
	'InvestorCountryOfResidence': FixFieldDescriptor('InvestorCountryOfResidence', 475, 'COUNTRY', str),
	'IssueDate': FixFieldDescriptor('IssueDate', 225, 'LOCALMKTDATE', str),
	'Issuer': FixFieldDescriptor('Issuer', 106, 'STRING', str),
	'LastCapacity': FixFieldDescriptor('LastCapacity', 29, 'CHAR', str),
	'LastForwardPoints': FixFieldDescriptor('LastForwardPoints', 195, 'PRICEOFFSET', float),
	'LastForwardPoints2': FixFieldDescriptor('LastForwardPoints2', 641, 'PRICEOFFSET', float),
	'LastFragment': FixFieldDescriptor('LastFragment', 893, 'BOOLEAN', str),
	'LastLiquidityInd': FixFieldDescriptor('LastLiquidityInd', 851, 'INT', int),
	'LastMkt': FixFieldDescriptor('LastMkt', 30, 'EXCHANGE', str),
	'LastMsgSeqNumProcessed': FixFieldDescriptor('LastMsgSeqNumProcessed', 369, 'SEQNUM', int),
	'LastNetworkResponseID': FixFieldDescriptor('LastNetworkResponseID', 934, 'STRING', str),
	'LastParPx': FixFieldDescriptor('LastParPx', 669, 'PRICE', float),
	'LastPx': FixFieldDescriptor('LastPx', 31, 'PRICE', float),
	'LastQty': FixFieldDescriptor('LastQty', 32, 'QTY', float),
	'LastRptRequested': FixFieldDescriptor('LastRptRequested', 912, 'BOOLEAN', str),
	'LastSpotRate': FixFieldDescriptor('LastSpotRate', 194, 'PRICE', float),
	'LastUpdateTime': FixFieldDescriptor('LastUpdateTime', 779, 'UTCTIMESTAMP', str),
	'LeavesQty': FixFieldDescriptor('LeavesQty', 151, 'QTY', float),
	'LegAllocAccount': FixFieldDescriptor('LegAllocAccount', 671, 'STRING', str),
	'LegAllocAcctIDSource': FixFieldDescriptor('LegAllocAcctIDSource', 674, 'STRING', str),
	'LegAllocQty': FixFieldDescriptor('LegAllocQty', 673, 'QTY', float),
	'LegBenchmarkCurveCurrency': FixFieldDescriptor('LegBenchmarkCurveCurrency', 676, 'CURRENCY', str),
	'LegBenchmarkCurveName': FixFieldDescriptor('LegBenchmarkCurveName', 677, 'STRING', str),
	'LegBenchmarkCurvePoint': FixFieldDescriptor('LegBenchmarkCurvePoint', 678, 'STRING', str),
	'LegBenchmarkPrice': FixFieldDescriptor('LegBenchmarkPrice', 679, 'PRICE', float),
	'LegBenchmarkPriceType': FixFieldDescriptor('LegBenchmarkPriceType', 680, 'INT', int),
	'LegBidPx': FixFieldDescriptor('LegBidPx', 681, 'PRICE', float),
	'LegCFICode': FixFieldDescriptor('LegCFICode', 608, 'STRING', str),
	'LegContractMultiplier': FixFieldDescriptor('LegContractMultiplier', 614, 'FLOAT', float),
	'LegContractSettlMonth': FixFieldDescriptor('LegContractSettlMonth', 955, 'MONTHYEAR', str),
	'LegCountryOfIssue': FixFieldDescriptor('LegCountryOfIssue', 596, 'COUNTRY', str),
	'LegCouponPaymentDate': FixFieldDescriptor('LegCouponPaymentDate', 248, 'LOCALMKTDATE', str),
	'LegCouponRate': FixFieldDescriptor('LegCouponRate', 615, 'PERCENTAGE', float),
	'LegCoveredOrUncovered': FixFieldDescriptor('LegCoveredOrUncovered', 565, 'INT', int),
	'LegCreditRating': FixFieldDescriptor('LegCreditRating', 257, 'STRING', str),
	'LegCurrency': FixFieldDescriptor('LegCurrency', 556, 'CURRENCY', str),
	'LegDatedDate': FixFieldDescriptor('LegDatedDate', 739, 'LOCALMKTDATE', str),
	'LegFactor': FixFieldDescriptor('LegFactor', 253, 'FLOAT', float),
	'LegIOIQty': FixFieldDescriptor('LegIOIQty', 682, 'STRING', str),
	'LegIndividualAllocID': FixFieldDescriptor('LegIndividualAllocID', 672, 'STRING', str),
	'LegInstrRegistry': FixFieldDescriptor('LegInstrRegistry', 599, 'STRING', str),
	'LegInterestAccrualDate': FixFieldDescriptor('LegInterestAccrualDate', 956, 'LOCALMKTDATE', str),
	'LegIssueDate': FixFieldDescriptor('LegIssueDate', 249, 'LOCALMKTDATE', str),
	'LegIssuer': FixFieldDescriptor('LegIssuer', 617, 'STRING', str),
	'LegLastPx': FixFieldDescriptor('LegLastPx', 637, 'PRICE', float),
	'LegLocaleOfIssue': FixFieldDescriptor('LegLocaleOfIssue', 598, 'STRING', str),
	'LegMaturityDate': FixFieldDescriptor('LegMaturityDate', 611, 'LOCALMKTDATE', str),
	'LegMaturityMonthYear': FixFieldDescriptor('LegMaturityMonthYear', 610, 'MONTHYEAR', str),
	'LegOfferPx': FixFieldDescriptor('LegOfferPx', 684, 'PRICE', float),
	'LegOptAttribute': FixFieldDescriptor('LegOptAttribute', 613, 'CHAR', str),
	'LegOrderQty': FixFieldDescriptor('LegOrderQty', 685, 'QTY', float),
	'LegPool': FixFieldDescriptor('LegPool', 740, 'STRING', str),
	'LegPositionEffect': FixFieldDescriptor('LegPositionEffect', 564, 'CHAR', str),
	'LegPrice': FixFieldDescriptor('LegPrice', 566, 'PRICE', float),
	'LegPriceType': FixFieldDescriptor('LegPriceType', 686, 'INT', int),
	'LegProduct': FixFieldDescriptor('LegProduct', 607, 'INT', int),
	'LegQty': FixFieldDescriptor('LegQty', 687, 'QTY', float),
	'LegRatioQty': FixFieldDescriptor('LegRatioQty', 623, 'FLOAT', float),
	'LegRedemptionDate': FixFieldDescriptor('LegRedemptionDate', 254, 'LOCALMKTDATE', str),
	'LegRefID': FixFieldDescriptor('LegRefID', 654, 'STRING', str),
	'LegRepoCollateralSecurityType': FixFieldDescriptor('LegRepoCollateralSecurityType', 250, 'INT', int),
	'LegRepurchaseRate': FixFieldDescriptor('LegRepurchaseRate', 252, 'PERCENTAGE', float),
	'LegRepurchaseTerm': FixFieldDescriptor('LegRepurchaseTerm', 251, 'INT', int),
	'LegSecurityAltID': FixFieldDescriptor('LegSecurityAltID', 605, 'STRING', str),
	'LegSecurityAltIDSource': FixFieldDescriptor('LegSecurityAltIDSource', 606, 'STRING', str),
	'LegSecurityDesc': FixFieldDescriptor('LegSecurityDesc', 620, 'STRING', str),
	'LegSecurityExchange': FixFieldDescriptor('LegSecurityExchange', 616, 'EXCHANGE', str),
	'LegSecurityID': FixFieldDescriptor('LegSecurityID', 602, 'STRING', str),
	'LegSecurityIDSource': FixFieldDescriptor('LegSecurityIDSource', 603, 'STRING', str),
	'LegSecuritySubType': FixFieldDescriptor('LegSecuritySubType', 764, 'STRING', str),
	'LegSecurityType': FixFieldDescriptor('LegSecurityType', 609, 'STRING', str),
	'LegSettlCurrency': FixFieldDescriptor('LegSettlCurrency', 675, 'CURRENCY', str),
	'LegSettlDate': FixFieldDescriptor('LegSettlDate', 588, 'LOCALMKTDATE', str),
	'LegSettlType': FixFieldDescriptor('LegSettlType', 587, 'CHAR', str),
	'LegSide': FixFieldDescriptor('LegSide', 624, 'CHAR', str),
	'LegStateOrProvinceOfIssue': FixFieldDescriptor('LegStateOrProvinceOfIssue', 597, 'STRING', str),
	'LegStipulationType': FixFieldDescriptor('LegStipulationType', 688, 'STRING', str),
	'LegStipulationValue': FixFieldDescriptor('LegStipulationValue', 689, 'STRING', str),
	'LegStrikeCurrency': FixFieldDescriptor('LegStrikeCurrency', 942, 'CURRENCY', str),
	'LegStrikePrice': FixFieldDescriptor('LegStrikePrice', 612, 'PRICE', float),
	'LegSwapType': FixFieldDescriptor('LegSwapType', 690, 'INT', int),
	'LegSymbol': FixFieldDescriptor('LegSymbol', 600, 'STRING', str),
	'LegSymbolSfx': FixFieldDescriptor('LegSymbolSfx', 601, 'STRING', str),
	'LegalConfirm': FixFieldDescriptor('LegalConfirm', 650, 'BOOLEAN', str),
	'LinesOfText': FixGroupDescriptor('LinesOfText', 33),
	'LiquidityIndType': FixFieldDescriptor('LiquidityIndType', 409, 'INT', int),
	'LiquidityNumSecurities': FixFieldDescriptor('LiquidityNumSecurities', 441, 'INT', int),
	'LiquidityPctHigh': FixFieldDescriptor('LiquidityPctHigh', 403, 'PERCENTAGE', float),
	'LiquidityPctLow': FixFieldDescriptor('LiquidityPctLow', 402, 'PERCENTAGE', float),
	'LiquidityValue': FixFieldDescriptor('LiquidityValue', 404, 'AMT', float),
	'ListExecInst': FixFieldDescriptor('ListExecInst', 69, 'STRING', str),
	'ListExecInstType': FixFieldDescriptor('ListExecInstType', 433, 'CHAR', str),
	'ListID': FixFieldDescriptor('ListID', 66, 'STRING', str),
	'ListName': FixFieldDescriptor('ListName', 392, 'STRING', str),
	'ListOrderStatus': FixFieldDescriptor('ListOrderStatus', 431, 'INT', int),
	'ListSeqNo': FixFieldDescriptor('ListSeqNo', 67, 'INT', int),
	'ListStatusText': FixFieldDescriptor('ListStatusText', 444, 'STRING', str),
	'ListStatusType': FixFieldDescriptor('ListStatusType', 429, 'INT', int),
	'LocaleOfIssue': FixFieldDescriptor('LocaleOfIssue', 472, 'STRING', str),
	'LocateReqd': FixFieldDescriptor('LocateReqd', 114, 'BOOLEAN', str),
	'LocationID': FixFieldDescriptor('LocationID', 283, 'STRING', str),
	'LongQty': FixFieldDescriptor('LongQty', 704, 'QTY', float),
	'LowPx': FixFieldDescriptor('LowPx', 333, 'PRICE', float),
	'MDEntryBuyer': FixFieldDescriptor('MDEntryBuyer', 288, 'STRING', str),
	'MDEntryDate': FixFieldDescriptor('MDEntryDate', 272, 'UTCDATEONLY', str),
	'MDEntryID': FixFieldDescriptor('MDEntryID', 278, 'STRING', str),
	'MDEntryOriginator': FixFieldDescriptor('MDEntryOriginator', 282, 'STRING', str),
	'MDEntryPositionNo': FixFieldDescriptor('MDEntryPositionNo', 290, 'INT', int),
	'MDEntryPx': FixFieldDescriptor('MDEntryPx', 270, 'PRICE', float),
	'MDEntryRefID': FixFieldDescriptor('MDEntryRefID', 280, 'STRING', str),
	'MDEntrySeller': FixFieldDescriptor('MDEntrySeller', 289, 'STRING', str),
	'MDEntrySize': FixFieldDescriptor('MDEntrySize', 271, 'QTY', float),
	'MDEntryTime': FixFieldDescriptor('MDEntryTime', 273, 'UTCTIMEONLY', str),
	'MDEntryType': FixFieldDescriptor('MDEntryType', 269, 'CHAR', str),
	'MDImplicitDelete': FixFieldDescriptor('MDImplicitDelete', 547, 'BOOLEAN', str),
	'MDMkt': FixFieldDescriptor('MDMkt', 275, 'EXCHANGE', str),
	'MDReqID': FixFieldDescriptor('MDReqID', 262, 'STRING', str),
	'MDReqRejReason': FixFieldDescriptor('MDReqRejReason', 281, 'CHAR', str),
	'MDUpdateAction': FixFieldDescriptor('MDUpdateAction', 279, 'CHAR', str),
	'MDUpdateType': FixFieldDescriptor('MDUpdateType', 265, 'INT', int),
	'MailingDtls': FixFieldDescriptor('MailingDtls', 474, 'STRING', str),
	'MailingInst': FixFieldDescriptor('MailingInst', 482, 'STRING', str),
	'MarginExcess': FixFieldDescriptor('MarginExcess', 899, 'AMT', float),
	'MarginRatio': FixFieldDescriptor('MarginRatio', 898, 'PERCENTAGE', float),
	'MarketDepth': FixFieldDescriptor('MarketDepth', 264, 'INT', int),
	'MassCancelRejectReason': FixFieldDescriptor('MassCancelRejectReason', 532, 'CHAR', str),
	'MassCancelRequestType': FixFieldDescriptor('MassCancelRequestType', 530, 'CHAR', str),
	'MassCancelResponse': FixFieldDescriptor('MassCancelResponse', 531, 'CHAR', str),
	'MassStatusReqID': FixFieldDescriptor('MassStatusReqID', 584, 'STRING', str),
	'MassStatusReqType': FixFieldDescriptor('MassStatusReqType', 585, 'INT', int),
	'MatchStatus': FixFieldDescriptor('MatchStatus', 573, 'CHAR', str),
	'MatchType': FixFieldDescriptor('MatchType', 574, 'STRING', str),
	'MaturityDate': FixFieldDescriptor('MaturityDate', 541, 'LOCALMKTDATE', str),
	'MaturityMonthYear': FixFieldDescriptor('MaturityMonthYear', 200, 'MONTHYEAR', str),
	'MaturityNetMoney': FixFieldDescriptor('MaturityNetMoney', 890, 'AMT', float),
	'MaxFloor': FixFieldDescriptor('MaxFloor', 111, 'QTY', float),
	'MaxMessageSize': FixFieldDescriptor('MaxMessageSize', 383, 'LENGTH', str),
	'MaxShow': FixFieldDescriptor('MaxShow', 210, 'QTY', float),
	'MessageEncoding': FixFieldDescriptor('MessageEncoding', 347, 'STRING', str),
	'MidPx': FixFieldDescriptor('MidPx', 631, 'PRICE', float),
	'MidYield': FixFieldDescriptor('MidYield', 633, 'PERCENTAGE', float),
	'MinBidSize': FixFieldDescriptor('MinBidSize', 647, 'QTY', float),
	'MinOfferSize': FixFieldDescriptor('MinOfferSize', 648, 'QTY', float),
	'MinQty': FixFieldDescriptor('MinQty', 110, 'QTY', float),
	'MinTradeVol': FixFieldDescriptor('MinTradeVol', 562, 'QTY', float),
	'MiscFeeAmt': FixFieldDescriptor('MiscFeeAmt', 137, 'AMT', float),
	'MiscFeeBasis': FixFieldDescriptor('MiscFeeBasis', 891, 'INT', int),
	'MiscFeeCurr': FixFieldDescriptor('MiscFeeCurr', 138, 'CURRENCY', str),
	'MiscFeeType': FixFieldDescriptor('MiscFeeType', 139, 'CHAR', str),
	'MktBidPx': FixFieldDescriptor('MktBidPx', 645, 'PRICE', float),
	'MktOfferPx': FixFieldDescriptor('MktOfferPx', 646, 'PRICE', float),
	'MoneyLaunderingStatus': FixFieldDescriptor('MoneyLaunderingStatus', 481, 'CHAR', str),
	'MsgDirection': FixFieldDescriptor('MsgDirection', 385, 'CHAR', str),
	'MsgSeqNum': FixFieldDescriptor('MsgSeqNum', 34, 'SEQNUM', int),
	'MsgType': FixFieldDescriptor('MsgType', 35, 'STRING', str),
	'MultiLegReportingType': FixFieldDescriptor('MultiLegReportingType', 442, 'CHAR', str),
	'MultiLegRptTypeReq': FixFieldDescriptor('MultiLegRptTypeReq', 563, 'INT', int),
	'Nested2PartyID': FixFieldDescriptor('Nested2PartyID', 757, 'STRING', str),
	'Nested2PartyIDSource': FixFieldDescriptor('Nested2PartyIDSource', 758, 'CHAR', str),
	'Nested2PartyRole': FixFieldDescriptor('Nested2PartyRole', 759, 'INT', int),
	'Nested2PartySubID': FixFieldDescriptor('Nested2PartySubID', 760, 'STRING', str),
	'Nested2PartySubIDType': FixFieldDescriptor('Nested2PartySubIDType', 807, 'INT', int),
	'Nested3PartyID': FixFieldDescriptor('Nested3PartyID', 949, 'STRING', str),
	'Nested3PartyIDSource': FixFieldDescriptor('Nested3PartyIDSource', 950, 'CHAR', str),
	'Nested3PartyRole': FixFieldDescriptor('Nested3PartyRole', 951, 'INT', int),
	'Nested3PartySubID': FixFieldDescriptor('Nested3PartySubID', 953, 'STRING', str),
	'Nested3PartySubIDType': FixFieldDescriptor('Nested3PartySubIDType', 954, 'INT', int),
	'NestedPartyID': FixFieldDescriptor('NestedPartyID', 524, 'STRING', str),
	'NestedPartyIDSource': FixFieldDescriptor('NestedPartyIDSource', 525, 'CHAR', str),
	'NestedPartyRole': FixFieldDescriptor('NestedPartyRole', 538, 'INT', int),
	'NestedPartySubID': FixFieldDescriptor('NestedPartySubID', 545, 'STRING', str),
	'NestedPartySubIDType': FixFieldDescriptor('NestedPartySubIDType', 805, 'INT', int),
	'NetChgPrevDay': FixFieldDescriptor('NetChgPrevDay', 451, 'PRICEOFFSET', float),
	'NetGrossInd': FixFieldDescriptor('NetGrossInd', 430, 'INT', int),
	'NetMoney': FixFieldDescriptor('NetMoney', 118, 'AMT', float),
	'NetworkRequestID': FixFieldDescriptor('NetworkRequestID', 933, 'STRING', str),
	'NetworkRequestType': FixFieldDescriptor('NetworkRequestType', 935, 'INT', int),
	'NetworkResponseID': FixFieldDescriptor('NetworkResponseID', 932, 'STRING', str),
	'NetworkStatusResponseType': FixFieldDescriptor('NetworkStatusResponseType', 937, 'INT', int),
	'NewPassword': FixFieldDescriptor('NewPassword', 925, 'STRING', str),
	'NewSeqNo': FixFieldDescriptor('NewSeqNo', 36, 'SEQNUM', int),
	'NextExpectedMsgSeqNum': FixFieldDescriptor('NextExpectedMsgSeqNum', 789, 'SEQNUM', int),
	'NoAffectedOrders': FixFieldDescriptor('NoAffectedOrders', 534, 'INT', int),
	'NoAllocs': FixGroupDescriptor('NoAllocs', 78),
	'NoAltMDSource': FixGroupDescriptor('NoAltMDSource', 816),
	'NoBidComponents': FixGroupDescriptor('NoBidComponents', 420),
	'NoBidDescriptors': FixGroupDescriptor('NoBidDescriptors', 398),
	'NoCapacities': FixGroupDescriptor('NoCapacities', 862),
	'NoClearingInstructions': FixFieldDescriptor('NoClearingInstructions', 576, 'INT', int),
	'NoCollInquiryQualifier': FixGroupDescriptor('NoCollInquiryQualifier', 938),
	'NoCompIDs': FixGroupDescriptor('NoCompIDs', 936),
	'NoContAmts': FixGroupDescriptor('NoContAmts', 518),
	'NoContraBrokers': FixGroupDescriptor('NoContraBrokers', 382),
	'NoDates': FixGroupDescriptor('NoDates', 580),
	'NoDistribInsts': FixGroupDescriptor('NoDistribInsts', 510),
	'NoDlvyInst': FixGroupDescriptor('NoDlvyInst', 85),
	'NoEvents': FixGroupDescriptor('NoEvents', 864),
	'NoExecs': FixGroupDescriptor('NoExecs', 124),
	'NoHops': FixGroupDescriptor('NoHops', 627),
	'NoIOIQualifiers': FixGroupDescriptor('NoIOIQualifiers', 199),
	'NoInstrAttrib': FixGroupDescriptor('NoInstrAttrib', 870),
	'NoLegAllocs': FixGroupDescriptor('NoLegAllocs', 670),
	'NoLegSecurityAltID': FixFieldDescriptor('NoLegSecurityAltID', 604, 'STRING', str),
	'NoLegStipulations': FixGroupDescriptor('NoLegStipulations', 683),
	'NoLegs': FixGroupDescriptor('NoLegs', 555),
	'NoMDEntries': FixGroupDescriptor('NoMDEntries', 268),
	'NoMDEntryTypes': FixGroupDescriptor('NoMDEntryTypes', 267),
	'NoMiscFees': FixGroupDescriptor('NoMiscFees', 136),
	'NoMsgTypes': FixGroupDescriptor('NoMsgTypes', 384),
	'NoNested2PartyIDs': FixGroupDescriptor('NoNested2PartyIDs', 756),
	'NoNested2PartySubIDs': FixGroupDescriptor('NoNested2PartySubIDs', 806),
	'NoNested3PartyIDs': FixGroupDescriptor('NoNested3PartyIDs', 948),
	'NoNested3PartySubIDs': FixGroupDescriptor('NoNested3PartySubIDs', 952),
	'NoNestedPartyIDs': FixGroupDescriptor('NoNestedPartyIDs', 539),
	'NoNestedPartySubIDs': FixGroupDescriptor('NoNestedPartySubIDs', 804),
	'NoOrders': FixGroupDescriptor('NoOrders', 73),
	'NoPartyIDs': FixGroupDescriptor('NoPartyIDs', 453),
	'NoPartySubIDs': FixGroupDescriptor('NoPartySubIDs', 802),
	'NoPosAmt': FixGroupDescriptor('NoPosAmt', 753),
	'NoPositions': FixGroupDescriptor('NoPositions', 702),
	'NoQuoteEntries': FixGroupDescriptor('NoQuoteEntries', 295),
	'NoQuoteQualifiers': FixGroupDescriptor('NoQuoteQualifiers', 735),
	'NoQuoteSets': FixGroupDescriptor('NoQuoteSets', 296),
	'NoRegistDtls': FixGroupDescriptor('NoRegistDtls', 473),
	'NoRelatedSym': FixGroupDescriptor('NoRelatedSym', 146),
	'NoRoutingIDs': FixGroupDescriptor('NoRoutingIDs', 215),
	'NoRpts': FixGroupDescriptor('NoRpts', 82),
	'NoSecurityAltID': FixGroupDescriptor('NoSecurityAltID', 454),
	'NoSecurityTypes': FixGroupDescriptor('NoSecurityTypes', 558),
	'NoSettlInst': FixGroupDescriptor('NoSettlInst', 778),
	'NoSettlPartyIDs': FixGroupDescriptor('NoSettlPartyIDs', 781),
	'NoSettlPartySubIDs': FixGroupDescriptor('NoSettlPartySubIDs', 801),
	'NoSides': FixGroupDescriptor('NoSides', 552),
	'NoStipulations': FixGroupDescriptor('NoStipulations', 232),
	'NoStrikes': FixGroupDescriptor('NoStrikes', 428),
	'NoTrades': FixGroupDescriptor('NoTrades', 897),
	'NoTradingSessions': FixGroupDescriptor('NoTradingSessions', 386),
	'NoTrdRegTimestamps': FixGroupDescriptor('NoTrdRegTimestamps', 768),
	'NoUnderlyingSecurityAltID': FixGroupDescriptor('NoUnderlyingSecurityAltID', 457),
	'NoUnderlyingStips': FixGroupDescriptor('NoUnderlyingStips', 887),
	'NoUnderlyings': FixGroupDescriptor('NoUnderlyings', 711),
	'NotifyBrokerOfCredit': FixFieldDescriptor('NotifyBrokerOfCredit', 208, 'BOOLEAN', str),
	'NumBidders': FixFieldDescriptor('NumBidders', 417, 'INT', int),
	'NumDaysInterest': FixFieldDescriptor('NumDaysInterest', 157, 'INT', int),
	'NumTickets': FixFieldDescriptor('NumTickets', 395, 'INT', int),
	'NumberOfOrders': FixFieldDescriptor('NumberOfOrders', 346, 'INT', int),
	'OddLot': FixFieldDescriptor('OddLot', 575, 'BOOLEAN', str),
	'OfferForwardPoints': FixFieldDescriptor('OfferForwardPoints', 191, 'PRICEOFFSET', float),
	'OfferForwardPoints2': FixFieldDescriptor('OfferForwardPoints2', 643, 'PRICEOFFSET', float),
	'OfferPx': FixFieldDescriptor('OfferPx', 133, 'PRICE', float),
	'OfferSize': FixFieldDescriptor('OfferSize', 135, 'QTY', float),
	'OfferSpotRate': FixFieldDescriptor('OfferSpotRate', 190, 'PRICE', float),
	'OfferYield': FixFieldDescriptor('OfferYield', 634, 'PERCENTAGE', float),
	'OnBehalfOfCompID': FixFieldDescriptor('OnBehalfOfCompID', 115, 'STRING', str),
	'OnBehalfOfLocationID': FixFieldDescriptor('OnBehalfOfLocationID', 144, 'STRING', str),
	'OnBehalfOfSubID': FixFieldDescriptor('OnBehalfOfSubID', 116, 'STRING', str),
	'OpenCloseSettlFlag': FixFieldDescriptor('OpenCloseSettlFlag', 286, 'MULTIPLEVALUESTRING', str),
	'OpenInterest': FixFieldDescriptor('OpenInterest', 746, 'AMT', float),
	'OptAttribute': FixFieldDescriptor('OptAttribute', 206, 'CHAR', str),
	'OrdRejReason': FixFieldDescriptor('OrdRejReason', 103, 'INT', int),
	'OrdStatus': FixFieldDescriptor('OrdStatus', 39, 'CHAR', str),
	'OrdStatusReqID': FixFieldDescriptor('OrdStatusReqID', 790, 'STRING', str),
	'OrdType': FixFieldDescriptor('OrdType', 40, 'CHAR', str),
	'OrderAvgPx': FixFieldDescriptor('OrderAvgPx', 799, 'PRICE', float),
	'OrderBookingQty': FixFieldDescriptor('OrderBookingQty', 800, 'QTY', float),
	'OrderCapacity': FixFieldDescriptor('OrderCapacity', 528, 'CHAR', str),
	'OrderCapacityQty': FixFieldDescriptor('OrderCapacityQty', 863, 'QTY', float),
	'OrderID': FixFieldDescriptor('OrderID', 37, 'STRING', str),
	'OrderInputDevice': FixFieldDescriptor('OrderInputDevice', 821, 'STRING', str),
	'OrderPercent': FixFieldDescriptor('OrderPercent', 516, 'PERCENTAGE', float),
	'OrderQty': FixFieldDescriptor('OrderQty', 38, 'QTY', float),
	'OrderQty2': FixFieldDescriptor('OrderQty2', 192, 'QTY', float),
	'OrderRestrictions': FixFieldDescriptor('OrderRestrictions', 529, 'MULTIPLEVALUESTRING', str),
	'OrigClOrdID': FixFieldDescriptor('OrigClOrdID', 41, 'STRING', str),
	'OrigCrossID': FixFieldDescriptor('OrigCrossID', 551, 'STRING', str),
	'OrigOrdModTime': FixFieldDescriptor('OrigOrdModTime', 586, 'UTCTIMESTAMP', str),
	'OrigPosReqRefID': FixFieldDescriptor('OrigPosReqRefID', 713, 'STRING', str),
	'OrigSendingTime': FixFieldDescriptor('OrigSendingTime', 122, 'UTCTIMESTAMP', str),
	'OrigTime': FixFieldDescriptor('OrigTime', 42, 'UTCTIMESTAMP', str),
	'OutMainCntryUIndex': FixFieldDescriptor('OutMainCntryUIndex', 412, 'AMT', float),
	'OutsideIndexPct': FixFieldDescriptor('OutsideIndexPct', 407, 'PERCENTAGE', float),
	'OwnerType': FixFieldDescriptor('OwnerType', 522, 'INT', int),
	'OwnershipType': FixFieldDescriptor('OwnershipType', 517, 'CHAR', str),
	'ParticipationRate': FixFieldDescriptor('ParticipationRate', 849, 'PERCENTAGE', float),
	'PartyID': FixFieldDescriptor('PartyID', 448, 'STRING', str),
	'PartyIDSource': FixFieldDescriptor('PartyIDSource', 447, 'CHAR', str),
	'PartyRole': FixFieldDescriptor('PartyRole', 452, 'INT', int),
	'PartySubID': FixFieldDescriptor('PartySubID', 523, 'STRING', str),
	'PartySubIDType': FixFieldDescriptor('PartySubIDType', 803, 'INT', int),
	'Password': FixFieldDescriptor('Password', 554, 'STRING', str),
	'PaymentDate': FixFieldDescriptor('PaymentDate', 504, 'LOCALMKTDATE', str),
	'PaymentMethod': FixFieldDescriptor('PaymentMethod', 492, 'INT', int),
	'PaymentRef': FixFieldDescriptor('PaymentRef', 476, 'STRING', str),
	'PaymentRemitterID': FixFieldDescriptor('PaymentRemitterID', 505, 'STRING', str),
	'PctAtRisk': FixFieldDescriptor('PctAtRisk', 869, 'PERCENTAGE', float),
	'PegLimitType': FixFieldDescriptor('PegLimitType', 837, 'INT', int),
	'PegMoveType': FixFieldDescriptor('PegMoveType', 835, 'INT', int),
	'PegOffsetType': FixFieldDescriptor('PegOffsetType', 836, 'INT', int),
	'PegOffsetValue': FixFieldDescriptor('PegOffsetValue', 211, 'FLOAT', float),
	'PegRoundDirection': FixFieldDescriptor('PegRoundDirection', 838, 'INT', int),
	'PegScope': FixFieldDescriptor('PegScope', 840, 'INT', int),
	'PeggedPrice': FixFieldDescriptor('PeggedPrice', 839, 'PRICE', float),
	'Pool': FixFieldDescriptor('Pool', 691, 'STRING', str),
	'PosAmt': FixFieldDescriptor('PosAmt', 708, 'AMT', float),
	'PosAmtType': FixFieldDescriptor('PosAmtType', 707, 'STRING', str),
	'PosMaintAction': FixFieldDescriptor('PosMaintAction', 712, 'INT', int),
	'PosMaintResult': FixFieldDescriptor('PosMaintResult', 723, 'INT', int),
	'PosMaintRptID': FixFieldDescriptor('PosMaintRptID', 721, 'STRING', str),
	'PosMaintRptRefID': FixFieldDescriptor('PosMaintRptRefID', 714, 'STRING', str),
	'PosMaintStatus': FixFieldDescriptor('PosMaintStatus', 722, 'INT', int),
	'PosQtyStatus': FixFieldDescriptor('PosQtyStatus', 706, 'INT', int),
	'PosReqID': FixFieldDescriptor('PosReqID', 710, 'STRING', str),
	'PosReqResult': FixFieldDescriptor('PosReqResult', 728, 'INT', int),
	'PosReqStatus': FixFieldDescriptor('PosReqStatus', 729, 'INT', int),
	'PosReqType': FixFieldDescriptor('PosReqType', 724, 'INT', int),
	'PosTransType': FixFieldDescriptor('PosTransType', 709, 'INT', int),
	'PosType': FixFieldDescriptor('PosType', 703, 'STRING', str),
	'PositionEffect': FixFieldDescriptor('PositionEffect', 77, 'CHAR', str),
	'PossDupFlag': FixFieldDescriptor('PossDupFlag', 43, 'BOOLEAN', str),
	'PossResend': FixFieldDescriptor('PossResend', 97, 'BOOLEAN', str),
	'PreallocMethod': FixFieldDescriptor('PreallocMethod', 591, 'CHAR', str),
	'PrevClosePx': FixFieldDescriptor('PrevClosePx', 140, 'PRICE', float),
	'PreviouslyReported': FixFieldDescriptor('PreviouslyReported', 570, 'BOOLEAN', str),
	'Price': FixFieldDescriptor('Price', 44, 'PRICE', float),
	'Price2': FixFieldDescriptor('Price2', 640, 'PRICE', float),
	'PriceDelta': FixFieldDescriptor('PriceDelta', 811, 'FLOAT', float),
	'PriceImprovement': FixFieldDescriptor('PriceImprovement', 639, 'PRICEOFFSET', float),
	'PriceType': FixFieldDescriptor('PriceType', 423, 'INT', int),
	'PriorSettlPrice': FixFieldDescriptor('PriorSettlPrice', 734, 'PRICE', float),
	'PriorSpreadIndicator': FixFieldDescriptor('PriorSpreadIndicator', 720, 'BOOLEAN', str),
	'PriorityIndicator': FixFieldDescriptor('PriorityIndicator', 638, 'INT', int),
	'ProcessCode': FixFieldDescriptor('ProcessCode', 81, 'CHAR', str),
	'Product': FixFieldDescriptor('Product', 460, 'INT', int),
	'ProgPeriodInterval': FixFieldDescriptor('ProgPeriodInterval', 415, 'INT', int),
	'ProgRptReqs': FixFieldDescriptor('ProgRptReqs', 414, 'INT', int),
	'PublishTrdIndicator': FixFieldDescriptor('PublishTrdIndicator', 852, 'BOOLEAN', str),
	'QtyType': FixFieldDescriptor('QtyType', 854, 'INT', int),
	'Quantity': FixFieldDescriptor('Quantity', 53, 'QTY', float),
	'QuantityType': FixFieldDescriptor('QuantityType', 465, 'INT', int),
	'QuoteCancelType': FixFieldDescriptor('QuoteCancelType', 298, 'INT', int),
	'QuoteCondition': FixFieldDescriptor('QuoteCondition', 276, 'MULTIPLEVALUESTRING', str),
	'QuoteEntryID': FixFieldDescriptor('QuoteEntryID', 299, 'STRING', str),
	'QuoteEntryRejectReason': FixFieldDescriptor('QuoteEntryRejectReason', 368, 'INT', int),
	'QuoteID': FixFieldDescriptor('QuoteID', 117, 'STRING', str),
	'QuotePriceType': FixFieldDescriptor('QuotePriceType', 692, 'INT', int),
	'QuoteQualifier': FixFieldDescriptor('QuoteQualifier', 695, 'CHAR', str),
	'QuoteRejectReason': FixFieldDescriptor('QuoteRejectReason', 300, 'INT', int),
	'QuoteReqID': FixFieldDescriptor('QuoteReqID', 131, 'STRING', str),
	'QuoteRequestRejectReason': FixFieldDescriptor('QuoteRequestRejectReason', 658, 'INT', int),
	'QuoteRequestType': FixFieldDescriptor('QuoteRequestType', 303, 'INT', int),
	'QuoteRespID': FixFieldDescriptor('QuoteRespID', 693, 'STRING', str),
	'QuoteRespType': FixFieldDescriptor('QuoteRespType', 694, 'INT', int),
	'QuoteResponseLevel': FixFieldDescriptor('QuoteResponseLevel', 301, 'INT', int),
	'QuoteSetID': FixFieldDescriptor('QuoteSetID', 302, 'STRING', str),
	'QuoteSetValidUntilTime': FixFieldDescriptor('QuoteSetValidUntilTime', 367, 'UTCTIMESTAMP', str),
	'QuoteStatus': FixFieldDescriptor('QuoteStatus', 297, 'INT', int),
	'QuoteStatusReqID': FixFieldDescriptor('QuoteStatusReqID', 649, 'STRING', str),
	'QuoteType': FixFieldDescriptor('QuoteType', 537, 'INT', int),
	'RFQReqID': FixFieldDescriptor('RFQReqID', 644, 'STRING', str),
	'RawData': FixFieldDescriptor('RawData', 96, 'DATA', str),
	'RawDataLength': FixFieldDescriptor('RawDataLength', 95, 'LENGTH', str),
	'RedemptionDate': FixFieldDescriptor('RedemptionDate', 240, 'LOCALMKTDATE', str),
	'RefAllocID': FixFieldDescriptor('RefAllocID', 72, 'STRING', str),
	'RefCompID': FixFieldDescriptor('RefCompID', 930, 'STRING', str),
	'RefMsgType': FixFieldDescriptor('RefMsgType', 372, 'STRING', str),
	'RefSeqNum': FixFieldDescriptor('RefSeqNum', 45, 'SEQNUM', int),
	'RefSubID': FixFieldDescriptor('RefSubID', 931, 'STRING', str),
	'RefTagID': FixFieldDescriptor('RefTagID', 371, 'INT', int),
	'RegistAcctType': FixFieldDescriptor('RegistAcctType', 493, 'STRING', str),
	'RegistDtls': FixFieldDescriptor('RegistDtls', 509, 'STRING', str),
	'RegistEmail': FixFieldDescriptor('RegistEmail', 511, 'STRING', str),
	'RegistID': FixFieldDescriptor('RegistID', 513, 'STRING', str),
	'RegistRefID': FixFieldDescriptor('RegistRefID', 508, 'STRING', str),
	'RegistRejReasonCode': FixFieldDescriptor('RegistRejReasonCode', 507, 'INT', int),
	'RegistRejReasonText': FixFieldDescriptor('RegistRejReasonText', 496, 'STRING', str),
	'RegistStatus': FixFieldDescriptor('RegistStatus', 506, 'CHAR', str),
	'RegistTransType': FixFieldDescriptor('RegistTransType', 514, 'CHAR', str),
	'RepoCollateralSecurityType': FixFieldDescriptor('RepoCollateralSecurityType', 239, 'INT', int),
	'ReportToExch': FixFieldDescriptor('ReportToExch', 113, 'BOOLEAN', str),
	'ReportedPx': FixFieldDescriptor('ReportedPx', 861, 'PRICE', float),
	'RepurchaseRate': FixFieldDescriptor('RepurchaseRate', 227, 'PERCENTAGE', float),
	'RepurchaseTerm': FixFieldDescriptor('RepurchaseTerm', 226, 'INT', int),
	'ResetSeqNumFlag': FixFieldDescriptor('ResetSeqNumFlag', 141, 'BOOLEAN', str),
	'ResponseDestination': FixFieldDescriptor('ResponseDestination', 726, 'STRING', str),
	'ResponseTransportType': FixFieldDescriptor('ResponseTransportType', 725, 'INT', int),
	'ReversalIndicator': FixFieldDescriptor('ReversalIndicator', 700, 'BOOLEAN', str),
	'RoundLot': FixFieldDescriptor('RoundLot', 561, 'QTY', float),
	'RoundingDirection': FixFieldDescriptor('RoundingDirection', 468, 'CHAR', str),
	'RoundingModulus': FixFieldDescriptor('RoundingModulus', 469, 'FLOAT', float),
	'RoutingID': FixFieldDescriptor('RoutingID', 217, 'STRING', str),
	'RoutingType': FixFieldDescriptor('RoutingType', 216, 'INT', int),
	'RptSeq': FixFieldDescriptor('RptSeq', 83, 'INT', int),
	'Scope': FixFieldDescriptor('Scope', 546, 'MULTIPLEVALUESTRING', str),
	'SecondaryAllocID': FixFieldDescriptor('SecondaryAllocID', 793, 'STRING', str),
	'SecondaryClOrdID': FixFieldDescriptor('SecondaryClOrdID', 526, 'STRING', str),
	'SecondaryExecID': FixFieldDescriptor('SecondaryExecID', 527, 'STRING', str),
	'SecondaryOrderID': FixFieldDescriptor('SecondaryOrderID', 198, 'STRING', str),
	'SecondaryTradeReportID': FixFieldDescriptor('SecondaryTradeReportID', 818, 'STRING', str),
	'SecondaryTradeReportRefID': FixFieldDescriptor('SecondaryTradeReportRefID', 881, 'STRING', str),
	'SecondaryTrdType': FixFieldDescriptor('SecondaryTrdType', 855, 'INT', int),
	'SecureData': FixFieldDescriptor('SecureData', 91, 'DATA', str),
	'SecureDataLen': FixFieldDescriptor('SecureDataLen', 90, 'LENGTH', str),
	'SecurityAltID': FixFieldDescriptor('SecurityAltID', 455, 'STRING', str),
	'SecurityAltIDSource': FixFieldDescriptor('SecurityAltIDSource', 456, 'STRING', str),
	'SecurityDesc': FixFieldDescriptor('SecurityDesc', 107, 'STRING', str),
	'SecurityExchange': FixFieldDescriptor('SecurityExchange', 207, 'EXCHANGE', str),
	'SecurityID': FixFieldDescriptor('SecurityID', 48, 'STRING', str),
	'SecurityIDSource': FixFieldDescriptor('SecurityIDSource', 22, 'STRING', str),
	'SecurityListRequestType': FixFieldDescriptor('SecurityListRequestType', 559, 'INT', int),
	'SecurityReqID': FixFieldDescriptor('SecurityReqID', 320, 'STRING', str),
	'SecurityRequestResult': FixFieldDescriptor('SecurityRequestResult', 560, 'INT', int),
	'SecurityRequestType': FixFieldDescriptor('SecurityRequestType', 321, 'INT', int),
	'SecurityResponseID': FixFieldDescriptor('SecurityResponseID', 322, 'STRING', str),
	'SecurityResponseType': FixFieldDescriptor('SecurityResponseType', 323, 'INT', int),
	'SecurityStatusReqID': FixFieldDescriptor('SecurityStatusReqID', 324, 'STRING', str),
	'SecuritySubType': FixFieldDescriptor('SecuritySubType', 762, 'STRING', str),
	'SecurityTradingStatus': FixFieldDescriptor('SecurityTradingStatus', 326, 'INT', int),
	'SecurityType': FixFieldDescriptor('SecurityType', 167, 'STRING', str),
	'SellVolume': FixFieldDescriptor('SellVolume', 331, 'QTY', float),
	'SellerDays': FixFieldDescriptor('SellerDays', 287, 'INT', int),
	'SenderCompID': FixFieldDescriptor('SenderCompID', 49, 'STRING', str),
	'SenderLocationID': FixFieldDescriptor('SenderLocationID', 142, 'STRING', str),
	'SenderSubID': FixFieldDescriptor('SenderSubID', 50, 'STRING', str),
	'SendingTime': FixFieldDescriptor('SendingTime', 52, 'UTCTIMESTAMP', str),
	'SessionRejectReason': FixFieldDescriptor('SessionRejectReason', 373, 'INT', int),
	'SettlCurrAmt': FixFieldDescriptor('SettlCurrAmt', 119, 'AMT', float),
	'SettlCurrBidFxRate': FixFieldDescriptor('SettlCurrBidFxRate', 656, 'FLOAT', float),
	'SettlCurrFxRate': FixFieldDescriptor('SettlCurrFxRate', 155, 'FLOAT', float),
	'SettlCurrFxRateCalc': FixFieldDescriptor('SettlCurrFxRateCalc', 156, 'CHAR', str),
	'SettlCurrOfferFxRate': FixFieldDescriptor('SettlCurrOfferFxRate', 657, 'FLOAT', float),
	'SettlCurrency': FixFieldDescriptor('SettlCurrency', 120, 'CURRENCY', str),
	'SettlDate': FixFieldDescriptor('SettlDate', 64, 'LOCALMKTDATE', str),
	'SettlDate2': FixFieldDescriptor('SettlDate2', 193, 'LOCALMKTDATE', str),
	'SettlDeliveryType': FixFieldDescriptor('SettlDeliveryType', 172, 'INT', int),
	'SettlInstID': FixFieldDescriptor('SettlInstID', 162, 'STRING', str),
	'SettlInstMode': FixFieldDescriptor('SettlInstMode', 160, 'CHAR', str),
	'SettlInstMsgID': FixFieldDescriptor('SettlInstMsgID', 777, 'STRING', str),
	'SettlInstRefID': FixFieldDescriptor('SettlInstRefID', 214, 'STRING', str),
	'SettlInstReqID': FixFieldDescriptor('SettlInstReqID', 791, 'STRING', str),
	'SettlInstReqRejCode': FixFieldDescriptor('SettlInstReqRejCode', 792, 'INT', int),
	'SettlInstSource': FixFieldDescriptor('SettlInstSource', 165, 'CHAR', str),
	'SettlInstTransType': FixFieldDescriptor('SettlInstTransType', 163, 'CHAR', str),
	'SettlPartyID': FixFieldDescriptor('SettlPartyID', 782, 'STRING', str),
	'SettlPartyIDSource': FixFieldDescriptor('SettlPartyIDSource', 783, 'CHAR', str),
	'SettlPartyRole': FixFieldDescriptor('SettlPartyRole', 784, 'INT', int),
	'SettlPartySubID': FixFieldDescriptor('SettlPartySubID', 785, 'STRING', str),
	'SettlPartySubIDType': FixFieldDescriptor('SettlPartySubIDType', 786, 'INT', int),
	'SettlPrice': FixFieldDescriptor('SettlPrice', 730, 'PRICE', float),
	'SettlPriceType': FixFieldDescriptor('SettlPriceType', 731, 'INT', int),
	'SettlSessID': FixFieldDescriptor('SettlSessID', 716, 'STRING', str),
	'SettlSessSubID': FixFieldDescriptor('SettlSessSubID', 717, 'STRING', str),
	'SettlType': FixFieldDescriptor('SettlType', 63, 'CHAR', str),
	'SharedCommission': FixFieldDescriptor('SharedCommission', 858, 'AMT', float),
	'ShortQty': FixFieldDescriptor('ShortQty', 705, 'QTY', float),
	'ShortSaleReason': FixFieldDescriptor('ShortSaleReason', 853, 'INT', int),
	'Side': FixFieldDescriptor('Side', 54, 'CHAR', str),
	'SideComplianceID': FixFieldDescriptor('SideComplianceID', 659, 'STRING', str),
	'SideMultiLegReportingType': FixFieldDescriptor('SideMultiLegReportingType', 752, 'INT', int),
	'SideValue1': FixFieldDescriptor('SideValue1', 396, 'AMT', float),
	'SideValue2': FixFieldDescriptor('SideValue2', 397, 'AMT', float),
	'SideValueInd': FixFieldDescriptor('SideValueInd', 401, 'INT', int),
	'Signature': FixFieldDescriptor('Signature', 89, 'DATA', str),
	'SignatureLength': FixFieldDescriptor('SignatureLength', 93, 'LENGTH', str),
	'SolicitedFlag': FixFieldDescriptor('SolicitedFlag', 377, 'BOOLEAN', str),
	'Spread': FixFieldDescriptor('Spread', 218, 'PRICEOFFSET', float),
	'StandInstDbID': FixFieldDescriptor('StandInstDbID', 171, 'STRING', str),
	'StandInstDbName': FixFieldDescriptor('StandInstDbName', 170, 'STRING', str),
	'StandInstDbType': FixFieldDescriptor('StandInstDbType', 169, 'INT', int),
	'StartCash': FixFieldDescriptor('StartCash', 921, 'AMT', float),
	'StartDate': FixFieldDescriptor('StartDate', 916, 'LOCALMKTDATE', str),
	'StateOrProvinceOfIssue': FixFieldDescriptor('StateOrProvinceOfIssue', 471, 'STRING', str),
	'StatusText': FixFieldDescriptor('StatusText', 929, 'STRING', str),
	'StatusValue': FixFieldDescriptor('StatusValue', 928, 'INT', int),
	'StipulationType': FixFieldDescriptor('StipulationType', 233, 'STRING', str),
	'StipulationValue': FixFieldDescriptor('StipulationValue', 234, 'STRING', str),
	'StopPx': FixFieldDescriptor('StopPx', 99, 'PRICE', float),
	'StrikeCurrency': FixFieldDescriptor('StrikeCurrency', 947, 'CURRENCY', str),
	'StrikePrice': FixFieldDescriptor('StrikePrice', 202, 'PRICE', float),
	'StrikeTime': FixFieldDescriptor('StrikeTime', 443, 'UTCTIMESTAMP', str),
	'Subject': FixFieldDescriptor('Subject', 147, 'STRING', str),
	'SubscriptionRequestType': FixFieldDescriptor('SubscriptionRequestType', 263, 'CHAR', str),
	'Symbol': FixFieldDescriptor('Symbol', 55, 'STRING', str),
	'SymbolSfx': FixFieldDescriptor('SymbolSfx', 65, 'STRING', str),
	'TargetCompID': FixFieldDescriptor('TargetCompID', 56, 'STRING', str),
	'TargetLocationID': FixFieldDescriptor('TargetLocationID', 143, 'STRING', str),
	'TargetStrategy': FixFieldDescriptor('TargetStrategy', 847, 'INT', int),
	'TargetStrategyParameters': FixFieldDescriptor('TargetStrategyParameters', 848, 'STRING', str),
	'TargetStrategyPerformance': FixFieldDescriptor('TargetStrategyPerformance', 850, 'FLOAT', float),
	'TargetSubID': FixFieldDescriptor('TargetSubID', 57, 'STRING', str),
	'TaxAdvantageType': FixFieldDescriptor('TaxAdvantageType', 495, 'INT', int),
	'TerminationType': FixFieldDescriptor('TerminationType', 788, 'INT', int),
	'TestMessageIndicator': FixFieldDescriptor('TestMessageIndicator', 464, 'BOOLEAN', str),
	'TestReqID': FixFieldDescriptor('TestReqID', 112, 'STRING', str),
	'Text': FixFieldDescriptor('Text', 58, 'STRING', str),
	'ThresholdAmount': FixFieldDescriptor('ThresholdAmount', 834, 'PRICEOFFSET', float),
	'TickDirection': FixFieldDescriptor('TickDirection', 274, 'CHAR', str),
	'TimeBracket': FixFieldDescriptor('TimeBracket', 943, 'STRING', str),
	'TimeInForce': FixFieldDescriptor('TimeInForce', 59, 'CHAR', str),
	'TotNoAllocs': FixFieldDescriptor('TotNoAllocs', 892, 'INT', int),
	'TotNoOrders': FixFieldDescriptor('TotNoOrders', 68, 'INT', int),
	'TotNoQuoteEntries': FixFieldDescriptor('TotNoQuoteEntries', 304, 'INT', int),
	'TotNoRelatedSym': FixFieldDescriptor('TotNoRelatedSym', 393, 'INT', int),
	'TotNoSecurityTypes': FixFieldDescriptor('TotNoSecurityTypes', 557, 'INT', int),
	'TotNoStrikes': FixFieldDescriptor('TotNoStrikes', 422, 'INT', int),
	'TotNumAssignmentReports': FixFieldDescriptor('TotNumAssignmentReports', 832, 'INT', int),
	'TotNumReports': FixFieldDescriptor('TotNumReports', 911, 'INT', int),
	'TotNumTradeReports': FixFieldDescriptor('TotNumTradeReports', 748, 'INT', int),
	'TotalAccruedInterestAmt': FixFieldDescriptor('TotalAccruedInterestAmt', 540, 'AMT', float),
	'TotalAffectedOrders': FixFieldDescriptor('TotalAffectedOrders', 533, 'INT', int),
	'TotalNetValue': FixFieldDescriptor('TotalNetValue', 900, 'AMT', float),
	'TotalNumPosReports': FixFieldDescriptor('TotalNumPosReports', 727, 'INT', int),
	'TotalTakedown': FixFieldDescriptor('TotalTakedown', 237, 'AMT', float),
	'TotalVolumeTraded': FixFieldDescriptor('TotalVolumeTraded', 387, 'QTY', float),
	'TradSesCloseTime': FixFieldDescriptor('TradSesCloseTime', 344, 'UTCTIMESTAMP', str),
	'TradSesEndTime': FixFieldDescriptor('TradSesEndTime', 345, 'UTCTIMESTAMP', str),
	'TradSesMethod': FixFieldDescriptor('TradSesMethod', 338, 'INT', int),
	'TradSesMode': FixFieldDescriptor('TradSesMode', 339, 'INT', int),
	'TradSesOpenTime': FixFieldDescriptor('TradSesOpenTime', 342, 'UTCTIMESTAMP', str),
	'TradSesPreCloseTime': FixFieldDescriptor('TradSesPreCloseTime', 343, 'UTCTIMESTAMP', str),
	'TradSesReqID': FixFieldDescriptor('TradSesReqID', 335, 'STRING', str),
	'TradSesStartTime': FixFieldDescriptor('TradSesStartTime', 341, 'UTCTIMESTAMP', str),
	'TradSesStatus': FixFieldDescriptor('TradSesStatus', 340, 'INT', int),
	'TradSesStatusRejReason': FixFieldDescriptor('TradSesStatusRejReason', 567, 'INT', int),
	'TradeAllocIndicator': FixFieldDescriptor('TradeAllocIndicator', 826, 'INT', int),
	'TradeCondition': FixFieldDescriptor('TradeCondition', 277, 'MULTIPLEVALUESTRING', str),
	'TradeDate': FixFieldDescriptor('TradeDate', 75, 'LOCALMKTDATE', str),
	'TradeInputDevice': FixFieldDescriptor('TradeInputDevice', 579, 'STRING', str),
	'TradeInputSource': FixFieldDescriptor('TradeInputSource', 578, 'STRING', str),
	'TradeLegRefID': FixFieldDescriptor('TradeLegRefID', 824, 'STRING', str),
	'TradeLinkID': FixFieldDescriptor('TradeLinkID', 820, 'STRING', str),
	'TradeOriginationDate': FixFieldDescriptor('TradeOriginationDate', 229, 'LOCALMKTDATE', str),
	'TradeReportID': FixFieldDescriptor('TradeReportID', 571, 'STRING', str),
	'TradeReportRefID': FixFieldDescriptor('TradeReportRefID', 572, 'STRING', str),
	'TradeReportRejectReason': FixFieldDescriptor('TradeReportRejectReason', 751, 'INT', int),
	'TradeReportTransType': FixFieldDescriptor('TradeReportTransType', 487, 'INT', int),
	'TradeReportType': FixFieldDescriptor('TradeReportType', 856, 'INT', int),
	'TradeRequestID': FixFieldDescriptor('TradeRequestID', 568, 'STRING', str),
	'TradeRequestResult': FixFieldDescriptor('TradeRequestResult', 749, 'INT', int),
	'TradeRequestStatus': FixFieldDescriptor('TradeRequestStatus', 750, 'INT', int),
	'TradeRequestType': FixFieldDescriptor('TradeRequestType', 569, 'INT', int),
	'TradedFlatSwitch': FixFieldDescriptor('TradedFlatSwitch', 258, 'BOOLEAN', str),
	'TradingSessionID': FixFieldDescriptor('TradingSessionID', 336, 'STRING', str),
	'TradingSessionSubID': FixFieldDescriptor('TradingSessionSubID', 625, 'STRING', str),
	'TransBkdTime': FixFieldDescriptor('TransBkdTime', 483, 'UTCTIMESTAMP', str),
	'TransactTime': FixFieldDescriptor('TransactTime', 60, 'UTCTIMESTAMP', str),
	'TransferReason': FixFieldDescriptor('TransferReason', 830, 'STRING', str),
	'TrdMatchID': FixFieldDescriptor('TrdMatchID', 880, 'STRING', str),
	'TrdRegTimestamp': FixFieldDescriptor('TrdRegTimestamp', 769, 'UTCTIMESTAMP', str),
	'TrdRegTimestampOrigin': FixFieldDescriptor('TrdRegTimestampOrigin', 771, 'STRING', str),
	'TrdRegTimestampType': FixFieldDescriptor('TrdRegTimestampType', 770, 'INT', int),
	'TrdRptStatus': FixFieldDescriptor('TrdRptStatus', 939, 'INT', int),
	'TrdSubType': FixFieldDescriptor('TrdSubType', 829, 'INT', int),
	'TrdType': FixFieldDescriptor('TrdType', 828, 'INT', int),
	'URLLink': FixFieldDescriptor('URLLink', 149, 'STRING', str),
	'UnderlyingCFICode': FixFieldDescriptor('UnderlyingCFICode', 463, 'STRING', str),
	'UnderlyingCPProgram': FixFieldDescriptor('UnderlyingCPProgram', 877, 'STRING', str),
	'UnderlyingCPRegType': FixFieldDescriptor('UnderlyingCPRegType', 878, 'STRING', str),
	'UnderlyingContractMultiplier': FixFieldDescriptor('UnderlyingContractMultiplier', 436, 'FLOAT', float),
	'UnderlyingCountryOfIssue': FixFieldDescriptor('UnderlyingCountryOfIssue', 592, 'COUNTRY', str),
	'UnderlyingCouponPaymentDate': FixFieldDescriptor('UnderlyingCouponPaymentDate', 241, 'LOCALMKTDATE', str),
	'UnderlyingCouponRate': FixFieldDescriptor('UnderlyingCouponRate', 435, 'PERCENTAGE', float),
	'UnderlyingCreditRating': FixFieldDescriptor('UnderlyingCreditRating', 256, 'STRING', str),
	'UnderlyingCurrency': FixFieldDescriptor('UnderlyingCurrency', 318, 'CURRENCY', str),
	'UnderlyingCurrentValue': FixFieldDescriptor('UnderlyingCurrentValue', 885, 'AMT', float),
	'UnderlyingDirtyPrice': FixFieldDescriptor('UnderlyingDirtyPrice', 882, 'PRICE', float),
	'UnderlyingEndPrice': FixFieldDescriptor('UnderlyingEndPrice', 883, 'PRICE', float),
	'UnderlyingEndValue': FixFieldDescriptor('UnderlyingEndValue', 886, 'AMT', float),
	'UnderlyingFactor': FixFieldDescriptor('UnderlyingFactor', 246, 'FLOAT', float),
	'UnderlyingInstrRegistry': FixFieldDescriptor('UnderlyingInstrRegistry', 595, 'STRING', str),
	'UnderlyingIssueDate': FixFieldDescriptor('UnderlyingIssueDate', 242, 'LOCALMKTDATE', str),
	'UnderlyingIssuer': FixFieldDescriptor('UnderlyingIssuer', 306, 'STRING', str),
	'UnderlyingLastPx': FixFieldDescriptor('UnderlyingLastPx', 651, 'PRICE', float),
	'UnderlyingLastQty': FixFieldDescriptor('UnderlyingLastQty', 652, 'QTY', float),
	'UnderlyingLocaleOfIssue': FixFieldDescriptor('UnderlyingLocaleOfIssue', 594, 'STRING', str),
	'UnderlyingMaturityDate': FixFieldDescriptor('UnderlyingMaturityDate', 542, 'LOCALMKTDATE', str),
	'UnderlyingMaturityMonthYear': FixFieldDescriptor('UnderlyingMaturityMonthYear', 313, 'MONTHYEAR', str),
	'UnderlyingOptAttribute': FixFieldDescriptor('UnderlyingOptAttribute', 317, 'CHAR', str),
	'UnderlyingProduct': FixFieldDescriptor('UnderlyingProduct', 462, 'INT', int),
	'UnderlyingPx': FixFieldDescriptor('UnderlyingPx', 810, 'PRICE', float),
	'UnderlyingQty': FixFieldDescriptor('UnderlyingQty', 879, 'QTY', float),
	'UnderlyingRedemptionDate': FixFieldDescriptor('UnderlyingRedemptionDate', 247, 'LOCALMKTDATE', str),
	'UnderlyingRepoCollateralSecurityType': FixFieldDescriptor('UnderlyingRepoCollateralSecurityType', 243, 'INT', int),
	'UnderlyingRepurchaseRate': FixFieldDescriptor('UnderlyingRepurchaseRate', 245, 'PERCENTAGE', float),
	'UnderlyingRepurchaseTerm': FixFieldDescriptor('UnderlyingRepurchaseTerm', 244, 'INT', int),
	'UnderlyingSecurityAltID': FixFieldDescriptor('UnderlyingSecurityAltID', 458, 'STRING', str),
	'UnderlyingSecurityAltIDSource': FixFieldDescriptor('UnderlyingSecurityAltIDSource', 459, 'STRING', str),
	'UnderlyingSecurityDesc': FixFieldDescriptor('UnderlyingSecurityDesc', 307, 'STRING', str),
	'UnderlyingSecurityExchange': FixFieldDescriptor('UnderlyingSecurityExchange', 308, 'EXCHANGE', str),
	'UnderlyingSecurityID': FixFieldDescriptor('UnderlyingSecurityID', 309, 'STRING', str),
	'UnderlyingSecurityIDSource': FixFieldDescriptor('UnderlyingSecurityIDSource', 305, 'STRING', str),
	'UnderlyingSecuritySubType': FixFieldDescriptor('UnderlyingSecuritySubType', 763, 'STRING', str),
	'UnderlyingSecurityType': FixFieldDescriptor('UnderlyingSecurityType', 310, 'STRING', str),
	'UnderlyingSettlPrice': FixFieldDescriptor('UnderlyingSettlPrice', 732, 'PRICE', float),
	'UnderlyingSettlPriceType': FixFieldDescriptor('UnderlyingSettlPriceType', 733, 'INT', int),
	'UnderlyingStartValue': FixFieldDescriptor('UnderlyingStartValue', 884, 'AMT', float),
	'UnderlyingStateOrProvinceOfIssue': FixFieldDescriptor('UnderlyingStateOrProvinceOfIssue', 593, 'STRING', str),
	'UnderlyingStipType': FixFieldDescriptor('UnderlyingStipType', 888, 'STRING', str),
	'UnderlyingStipValue': FixFieldDescriptor('UnderlyingStipValue', 889, 'STRING', str),
	'UnderlyingStrikeCurrency': FixFieldDescriptor('UnderlyingStrikeCurrency', 941, 'CURRENCY', str),
	'UnderlyingStrikePrice': FixFieldDescriptor('UnderlyingStrikePrice', 316, 'PRICE', float),
	'UnderlyingSymbol': FixFieldDescriptor('UnderlyingSymbol', 311, 'STRING', str),
	'UnderlyingSymbolSfx': FixFieldDescriptor('UnderlyingSymbolSfx', 312, 'STRING', str),
	'UnderlyingTradingSessionID': FixFieldDescriptor('UnderlyingTradingSessionID', 822, 'STRING', str),
	'UnderlyingTradingSessionSubID': FixFieldDescriptor('UnderlyingTradingSessionSubID', 823, 'STRING', str),
	'UnsolicitedIndicator': FixFieldDescriptor('UnsolicitedIndicator', 325, 'BOOLEAN', str),
	'Urgency': FixFieldDescriptor('Urgency', 61, 'CHAR', str),
	'UserRequestID': FixFieldDescriptor('UserRequestID', 923, 'STRING', str),
	'UserRequestType': FixFieldDescriptor('UserRequestType', 924, 'INT', int),
	'UserStatus': FixFieldDescriptor('UserStatus', 926, 'INT', int),
	'UserStatusText': FixFieldDescriptor('UserStatusText', 927, 'STRING', str),
	'Username': FixFieldDescriptor('Username', 553, 'STRING', str),
	'ValidUntilTime': FixFieldDescriptor('ValidUntilTime', 62, 'UTCTIMESTAMP', str),
	'ValueOfFutures': FixFieldDescriptor('ValueOfFutures', 408, 'AMT', float),
	'WaveNo': FixFieldDescriptor('WaveNo', 105, 'STRING', str),
	'WorkingIndicator': FixFieldDescriptor('WorkingIndicator', 636, 'BOOLEAN', str),
	'WtAverageLiquidity': FixFieldDescriptor('WtAverageLiquidity', 410, 'PERCENTAGE', float),
	'XmlData': FixFieldDescriptor('XmlData', 213, 'DATA', str),
	'XmlDataLen': FixFieldDescriptor('XmlDataLen', 212, 'LENGTH', str),
	'Yield': FixFieldDescriptor('Yield', 236, 'PERCENTAGE', float),
	'YieldCalcDate': FixFieldDescriptor('YieldCalcDate', 701, 'LOCALMKTDATE', str),
	'YieldRedemptionDate': FixFieldDescriptor('YieldRedemptionDate', 696, 'LOCALMKTDATE', str),
	'YieldRedemptionPrice': FixFieldDescriptor('YieldRedemptionPrice', 697, 'PRICE', float),
	'YieldRedemptionPriceType': FixFieldDescriptor('YieldRedemptionPriceType', 698, 'INT', int),
	'YieldType': FixFieldDescriptor('YieldType', 235, 'STRING', str),
}

_fix_message_types = {
	'Advertisement': ('7', True),
	'AllocationInstruction': ('J', True),
	'AllocationInstructionAck': ('P', True),
	'AllocationReport': ('AS', True),
	'AllocationReportAck': ('AT', True),
	'AssignmentReport': ('AW', True),
	'BidRequest': ('k', True),
	'BidResponse': ('l', True),
	'BusinessMessageReject': ('j', True),
	'CollateralAssignment': ('AY', True),
	'CollateralInquiry': ('BB', True),
	'CollateralInquiryAck': ('BG', True),
	'CollateralReport': ('BA', True),
	'CollateralRequest': ('AX', True),
	'CollateralResponse': ('AZ', True),
	'Confirmation': ('AK', True),
	'ConfirmationAck': ('AU', True),
	'ConfirmationRequest': ('BH', True),
	'CrossOrderCancelReplaceRequest': ('t', True),
	'CrossOrderCancelRequest': ('u', True),
	'DerivativeSecurityList': ('AA', True),
	'DerivativeSecurityListRequest': ('z', True),
	'DontKnowTrade': ('Q', True),
	'Email': ('C', True),
	'ExecutionReport': ('8', True),
	'Heartbeat': ('0', False),
	'IndicationOfInterest': ('6', True),
	'ListCancelRequest': ('K', True),
	'ListExecute': ('L', True),
	'ListStatus': ('N', True),
	'ListStatusRequest': ('M', True),
	'ListStrikePrice': ('m', True),
	'Logon': ('A', False),
	'Logout': ('5', False),
	'MarketDataIncrementalRefresh': ('X', True),
	'MarketDataRequest': ('V', True),
	'MarketDataRequestReject': ('Y', True),
	'MarketDataSnapshotFullRefresh': ('W', True),
	'MassQuote': ('i', True),
	'MassQuoteAcknowledgement': ('b', True),
	'MultilegOrderCancelReplaceRequest': ('AC', True),
	'NetworkStatusRequest': ('BD', True),
	'NewOrderCross': ('s', True),
	'NewOrderList': ('E', True),
	'NewOrderMultileg': ('AB', True),
	'NewOrderSingle': ('D', True),
	'News': ('B', True),
	'OrderCancelReject': ('9', True),
	'OrderCancelReplaceRequest': ('G', True),
	'OrderCancelRequest': ('F', True),
	'OrderMassCancelReport': ('r', True),
	'OrderMassCancelRequest': ('q', True),
	'OrderMassStatusRequest': ('AF', True),
	'OrderStatusRequest': ('H', True),
	'PositionMaintenanceReport': ('AM', True),
	'PositionMaintenanceRequest': ('AL', True),
	'PositionReport': ('AP', True),
	'Quote': ('S', True),
	'QuoteCancel': ('Z', True),
	'QuoteRequest': ('R', True),
	'QuoteRequestReject': ('AG', True),
	'QuoteResponse': ('AJ', True),
	'QuoteStatusReport': ('AI', True),
	'QuoteStatusRequest': ('a', True),
	'RFQRequest': ('AH', True),
	'RegistrationInstructions': ('o', True),
	'RegistrationInstructionsResponse': ('p', True),
	'Reject': ('3', False),
	'RequestForPositions': ('AN', True),
	'RequestForPositionsAck': ('AO', True),
	'ResendRequest': ('2', False),
	'SecurityDefinition': ('d', True),
	'SecurityDefinitionRequest': ('c', True),
	'SecurityList': ('y', True),
	'SecurityListRequest': ('x', True),
	'SecurityStatus': ('f', True),
	'SecurityStatusRequest': ('e', True),
	'SecurityTypeRequest': ('v', True),
	'SecurityTypes': ('w', True),
	'SequenceReset': ('4', False),
	'SettlementInstructionRequest': ('AV', True),
	'SettlementInstructions': ('T', True),
	'TestRequest': ('1', False),
	'TradeCaptureReport': ('AE', True),
	'TradeCaptureReportAck': ('AR', True),
	'TradeCaptureReportRequest': ('AD', True),
	'TradeCaptureReportRequestAck': ('AQ', True),
	'TradingSessionStatus': ('h', True),
	'TradingSessionStatusRequest': ('g', True),
	'UserRequest': ('BE', True),
	'UserResponse': ('BF', True),
}

_fix_group_types = {
	'LinesOfText': [
		(58, 'Text'),
		(354, 'EncodedTextLen'),
		(355, 'EncodedText'),
		],
	'NoAffectedOrders': [
		(41, 'OrigClOrdID'),
		(535, 'AffectedOrderID'),
		(536, 'AffectedSecondaryOrderID'),
		],
	'NoAllocs': [
		(79, 'AllocAccount'),
		(661, 'AllocAcctIDSource'),
		(736, 'AllocSettlCurrency'),
		(467, 'IndividualAllocID'),
		(80, 'AllocQty'),
		],
	'NoAltMDSource': [
		(817, 'AltMDSourceID'),
		],
	'NoBidComponents': [
		(66, 'ListID'),
		(421, 'Country'),
		(54, 'Side'),
		(44, 'Price'),
		(423, 'PriceType'),
		(406, 'FairValue'),
		(430, 'NetGrossInd'),
		(63, 'SettlType'),
		(64, 'SettlDate'),
		(336, 'TradingSessionID'),
		(625, 'TradingSessionSubID'),
		(58, 'Text'),
		(354, 'EncodedTextLen'),
		(355, 'EncodedText'),
		],
	'NoBidDescriptors': [
		(399, 'BidDescriptorType'),
		(400, 'BidDescriptor'),
		(401, 'SideValueInd'),
		(404, 'LiquidityValue'),
		(441, 'LiquidityNumSecurities'),
		(402, 'LiquidityPctLow'),
		(403, 'LiquidityPctHigh'),
		(405, 'EFPTrackingError'),
		(406, 'FairValue'),
		(407, 'OutsideIndexPct'),
		(408, 'ValueOfFutures'),
		],
	'NoCapacities': [
		(528, 'OrderCapacity'),
		(529, 'OrderRestrictions'),
		(863, 'OrderCapacityQty'),
		],
	'NoClearingInstructions': [
		(577, 'ClearingInstruction'),
		],
	'NoCollInquiryQualifier': [
		(896, 'CollInquiryQualifier'),
		],
	'NoCompIDs': [
		(930, 'RefCompID'),
		(931, 'RefSubID'),
		(283, 'LocationID'),
		(284, 'DeskID'),
		(928, 'StatusValue'),
		(929, 'StatusText'),
		],
	'NoContAmts': [
		(519, 'ContAmtType'),
		(520, 'ContAmtValue'),
		(521, 'ContAmtCurr'),
		],
	'NoContraBrokers': [
		(375, 'ContraBroker'),
		(337, 'ContraTrader'),
		(437, 'ContraTradeQty'),
		(438, 'ContraTradeTime'),
		(655, 'ContraLegRefID'),
		],
	'NoDates': [
		(75, 'TradeDate'),
		(60, 'TransactTime'),
		],
	'NoDistribInsts': [
		(477, 'DistribPaymentMethod'),
		(512, 'DistribPercentage'),
		(478, 'CashDistribCurr'),
		(498, 'CashDistribAgentName'),
		(499, 'CashDistribAgentCode'),
		(500, 'CashDistribAgentAcctNumber'),
		(501, 'CashDistribPayRef'),
		(502, 'CashDistribAgentAcctName'),
		],
	'NoDlvyInst': [
		(165, 'SettlInstSource'),
		(787, 'DlvyInstType'),
		],
	'NoEvents': [
		(865, 'EventType'),
		(866, 'EventDate'),
		(867, 'EventPx'),
		(868, 'EventText'),
		],
	'NoExecs': [
		(17, 'ExecID'),
		],
	'NoHops': [
		(628, 'HopCompID'),
		(629, 'HopSendingTime'),
		(630, 'HopRefID'),
		],
	'NoIOIQualifiers': [
		(104, 'IOIQualifier'),
		],
	'NoInstrAttrib': [
		(871, 'InstrAttribType'),
		(872, 'InstrAttribValue'),
		],
	'NoLegAllocs': [
		(671, 'LegAllocAccount'),
		(672, 'LegIndividualAllocID'),
		(673, 'LegAllocQty'),
		(674, 'LegAllocAcctIDSource'),
		(675, 'LegSettlCurrency'),
		],
	'NoLegSecurityAltID': [
		(605, 'LegSecurityAltID'),
		(606, 'LegSecurityAltIDSource'),
		],
	'NoLegStipulations': [
		(688, 'LegStipulationType'),
		(689, 'LegStipulationValue'),
		],
	'NoLegs': [
		],
	'NoMDEntries': [
		(279, 'MDUpdateAction'),
		(285, 'DeleteReason'),
		(269, 'MDEntryType'),
		(278, 'MDEntryID'),
		(280, 'MDEntryRefID'),
		],
	'NoMDEntryTypes': [
		(269, 'MDEntryType'),
		],
	'NoMiscFees': [
		(137, 'MiscFeeAmt'),
		(138, 'MiscFeeCurr'),
		(139, 'MiscFeeType'),
		(891, 'MiscFeeBasis'),
		],
	'NoMsgTypes': [
		(372, 'RefMsgType'),
		(385, 'MsgDirection'),
		],
	'NoNested2PartyIDs': [
		(757, 'Nested2PartyID'),
		(758, 'Nested2PartyIDSource'),
		(759, 'Nested2PartyRole'),
		],
	'NoNested2PartySubIDs': [
		(760, 'Nested2PartySubID'),
		(807, 'Nested2PartySubIDType'),
		],
	'NoNested3PartyIDs': [
		(949, 'Nested3PartyID'),
		(950, 'Nested3PartyIDSource'),
		(951, 'Nested3PartyRole'),
		],
	'NoNested3PartySubIDs': [
		(953, 'Nested3PartySubID'),
		(954, 'Nested3PartySubIDType'),
		],
	'NoNestedPartyIDs': [
		(524, 'NestedPartyID'),
		(525, 'NestedPartyIDSource'),
		(538, 'NestedPartyRole'),
		],
	'NoNestedPartySubIDs': [
		(545, 'NestedPartySubID'),
		(805, 'NestedPartySubIDType'),
		],
	'NoOrders': [
		(11, 'ClOrdID'),
		(37, 'OrderID'),
		(198, 'SecondaryOrderID'),
		(526, 'SecondaryClOrdID'),
		(66, 'ListID'),
		(38, 'OrderQty'),
		(799, 'OrderAvgPx'),
		(800, 'OrderBookingQty'),
		],
	'NoPartyIDs': [
		(448, 'PartyID'),
		(447, 'PartyIDSource'),
		(452, 'PartyRole'),
		],
	'NoPartySubIDs': [
		(523, 'PartySubID'),
		(803, 'PartySubIDType'),
		],
	'NoPosAmt': [
		(707, 'PosAmtType'),
		(708, 'PosAmt'),
		],
	'NoPositions': [
		(703, 'PosType'),
		(704, 'LongQty'),
		(705, 'ShortQty'),
		(706, 'PosQtyStatus'),
		],
	'NoQuoteEntries': [
		(299, 'QuoteEntryID'),
		],
	'NoQuoteQualifiers': [
		(695, 'QuoteQualifier'),
		],
	'NoQuoteSets': [
		(302, 'QuoteSetID'),
		(304, 'TotNoQuoteEntries'),
		(893, 'LastFragment'),
		],
	'NoRegistDtls': [
		(509, 'RegistDtls'),
		(511, 'RegistEmail'),
		(474, 'MailingDtls'),
		(482, 'MailingInst'),
		(522, 'OwnerType'),
		(486, 'DateOfBirth'),
		(475, 'InvestorCountryOfResidence'),
		],
	'NoRelatedSym': [
		(15, 'Currency'),
		(827, 'ExpirationCycle'),
		],
	'NoRoutingIDs': [
		(216, 'RoutingType'),
		(217, 'RoutingID'),
		],
	'NoSecurityAltID': [
		(455, 'SecurityAltID'),
		(456, 'SecurityAltIDSource'),
		],
	'NoSecurityTypes': [
		(167, 'SecurityType'),
		(762, 'SecuritySubType'),
		(460, 'Product'),
		(461, 'CFICode'),
		],
	'NoSettlInst': [
		(162, 'SettlInstID'),
		(163, 'SettlInstTransType'),
		(214, 'SettlInstRefID'),
		(54, 'Side'),
		(460, 'Product'),
		(167, 'SecurityType'),
		(461, 'CFICode'),
		(168, 'EffectiveTime'),
		(126, 'ExpireTime'),
		(779, 'LastUpdateTime'),
		(492, 'PaymentMethod'),
		(476, 'PaymentRef'),
		(488, 'CardHolderName'),
		(489, 'CardNumber'),
		(503, 'CardStartDate'),
		(490, 'CardExpDate'),
		(491, 'CardIssNum'),
		(504, 'PaymentDate'),
		(505, 'PaymentRemitterID'),
		],
	'NoSettlPartyIDs': [
		(782, 'SettlPartyID'),
		(783, 'SettlPartyIDSource'),
		(784, 'SettlPartyRole'),
		],
	'NoSettlPartySubIDs': [
		(785, 'SettlPartySubID'),
		(786, 'SettlPartySubIDType'),
		],
	'NoSides': [
		(54, 'Side'),
		(37, 'OrderID'),
		(198, 'SecondaryOrderID'),
		(11, 'ClOrdID'),
		(526, 'SecondaryClOrdID'),
		(66, 'ListID'),
		(1, 'Account'),
		(660, 'AcctIDSource'),
		(581, 'AccountType'),
		(81, 'ProcessCode'),
		(575, 'OddLot'),
		],
	'NoStipulations': [
		(233, 'StipulationType'),
		(234, 'StipulationValue'),
		],
	'NoStrikes': [
		],
	'NoTrades': [
		(571, 'TradeReportID'),
		(818, 'SecondaryTradeReportID'),
		],
	'NoTradingSessions': [
		(336, 'TradingSessionID'),
		(625, 'TradingSessionSubID'),
		],
	'NoTrdRegTimestamps': [
		(769, 'TrdRegTimestamp'),
		(770, 'TrdRegTimestampType'),
		(771, 'TrdRegTimestampOrigin'),
		],
	'NoUnderlyingSecurityAltID': [
		(458, 'UnderlyingSecurityAltID'),
		(459, 'UnderlyingSecurityAltIDSource'),
		],
	'NoUnderlyingStips': [
		(888, 'UnderlyingStipType'),
		(889, 'UnderlyingStipValue'),
		],
	'NoUnderlyings': [
		],
}

_fix_field_numbers = {}
for desc in _fix_field_types.values():
	_fix_field_numbers[desc.number]=desc


_fix_group_numbers = {}
for name, desc in _fix_group_types.items():
	_fix_group_numbers[_fix_field_types[name].number]=desc


_fix_msgtype_table = {}
for name in _fix_message_types:
	_fix_msgtype_table[_fix_message_types[name][0]]=name


